### ISSUE TITLE
Star 2.5.0c throws "std::bad_alloc" for large number of threads but not for few threads

### ISSUE THREAD

**Issue by ndaniel** [alexdobin/STAR#101]
STAR v2.5.0c throws this error on a server with 96 GB of RAM 
````
Jan 15 21:30:20 ..... Started STAR run
Jan 15 21:30:20 ..... Loading genome
Jan 15 21:30:21 ..... Started mapping
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
when using 16 threads but it is running fine when using 4 threads.

More precisely, this gives the error message from above
```
STAR \
--genomeSAindexNbases 14 \
--alignIntronMax 972692 \
--outFilterMatchNmin 17 \
--outSAMattributes NM \
--outFilterMatchNminOverLread 0.80 \
--outFilterScoreMinOverLread 0.80 \
--alignSplicedMateMapLminOverLmate 0.80 \
--alignSJstitchMismatchNmax 5 -1 5 5 \
--genomeDir test/g-g-b_s2/ \
--runThreadN 16 \
--seedSearchStartLmax 17 \
--limitOutSAMoneReadBytes 100000000 \
--alignTranscriptsPerReadNmax 1000000 \
--scoreGap -10000 \
--alignEndsType EndToEnd \
--readFilesIn test/s_1.fq \
 test/s_2.fq \
--outFileNamePrefix test/g-g-s-r-u/
```
but it runs successfully when in the above example the `--runThreadN 16` is changed into `--runThreadN 4`.

The genome for the above example is built like this:
```
STAR \
--genomeChrBinNbits 17 \
--genomeSAindexNbases 14 \
--runMode genomeGenerate \
--genomeSuffixLengthMax 10000 \
--runThreadN 16 \
--genomeDir test/g-g-b_s2/ \
--genomeFastaFiles test/g-g-b_s.fa \
--outFileNamePrefix test/g-g-b_s2_results/
```

[Here](https://www.dropbox.com/s/ub8djapcgcho4xl/logs.zip?dl=0) are the log files for the run which gives the error message and [here](https://www.dropbox.com/s/1d07aks3jad3ygu/test.zip?dl=0) are the files needed to reproduce the error.

**Comment by alexdobin** [comment]
Hi Daniel,

thanks for the detailed report and test files. I could reproduce the problem. The RAM consumption grows continuously with time indicating a memory leak,and it's also proportional to the number of threads you used. I will fix this problem, however, in the meantime, please try to use smaller value for the --alignTranscriptsPerReadNmax 1000000 - this parameter causes the memory leak. Did you have a specific reason to increase this value from the default 10000?

Cheers
Alex

**Comment by ndaniel** [comment]
Hi Alex,

thanks for the quick answer!

The above example of STAR parameters is used for mapping reads only on [IGH locus](http://www.genenames.org/cgi-bin/genefamilies/set/349). I have noticed that when mapping reads (or paired-reads) on IGH loci the "--alignTranscriptsPerReadNmax 10000" is not enough and many good and valid mappings are missed. I found thru trial and error that "--alignTranscriptsPerReadNmax 1000000" works really well for this case.

**Comment by ndaniel** [comment]
It looks like STAR v2.5.0c crashing depends on the Linux distribution used.

For example, on **Ubuntu 14.04.3 LTS** STAR is running just fine but on STAR is crashing on **CentOS release 5.10 (Final)**!!!

**Comment by alexdobin** [comment]
The RAM consumed  by --runThreadN 16 --alignTranscriptsPerReadNmax 1000000 should be 16*1000000bytes*1500bytes~24GB. This is what I see on my server. There was no memory leak as I suspected, rather, the allocation of so much RAM was slow and appeared as continuous increase in RAM usage.

On Ubuntu, with STAR that you compiled yourself, are you seeing 64GB of RAM used in the example you sent me?
Could you try to run dynamically linked bin/Linux_x86_64/STAR on both Ubuntu and CentOS?

I am using RHEL 6 which should be closer to CentOS than Ubuntu. However, I had to install my own gcc 4.7.0 for compiling the code, since earlier versions do not support c++11.

**Comment by ndaniel** [comment]
On **CentOS 5.1** this shows up by using `/usr/bin/time -v STAR ...`:
- static `Maximum resident set size (kbytes): 64639872`
- dynamic  `Maximum resident set size (kbytes): 1664` plus the following error messages 
```
/lib64/libz.so.1: no version information available (required by star/bin/Linux_x86_64/STAR)
/lib64/libz.so.1: no version information available (required by star/bin/Linux_x86_64/STAR)
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.13' not found (required by star/bin/Linux_x86_64/STAR)
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by star/bin/Linux_x86_64/STAR)
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by star/bin/Linux_x86_64/STAR)
/lib64/libc.so.6: version `GLIBC_2.7' not found (required by star/bin/Linux_x86_64/STAR)
```

On **Ubuntu 14.04.3 LTS** this shows up by using `/usr/bin/time -v STAR ...`:
- static `Maximum resident set size (kbytes): ....` (I will fill up later)
- dynamic  `Maximum resident set size (kbytes): ...` (I will fill up later)

**Comment by alexdobin** [comment]
Hi Daniel,

thanks for the tests!
On my server, I got
*Maximum resident set size (kbytes): 27452952*
which agrees with my expectations.

Hopefully, the number on Ubuntu dynamic/compiled will be close.

The dynamic version on CentOS 5.1 does not work because it requires newer glibc libraries.
And it looks like there is a problem with RAM management for the static executable...

**Comment by ndaniel** [comment]
On **Ubuntu 14.04.3 LTS** this shows up by using `/usr/bin/time -v STAR --runThreadN 16 ...`:
- static `Maximum resident set size (kbytes): 27452540` and `Elapsed (wall clock) time (h:mm:ss or m:ss): 1:23.02`, 
- dynamic  `Maximum resident set size (kbytes): 27454392`. and `Elapsed (wall clock) time (h:mm:ss or m:ss): 1:22.33`, and
- compiled `Maximum resident set size (kbytes): ` and `Elapsed (wall clock) time (h:mm:ss or m:ss): `.

On **Ubuntu 14.04.3 LTS** this shows up by using `/usr/bin/time -v STAR --runThreadN 32 ...`:
- static `Maximum resident set size (kbytes): 53325308` and `Elapsed (wall clock) time (h:mm:ss or m:ss): 2:00.67`, 
- dynamic  `Maximum resident set size (kbytes): 48682712` and `Elapsed (wall clock) time (h:mm:ss or m:ss): 5:24.13`, and
- compiled `Maximum resident set size (kbytes): ` and `Elapsed (wall clock) time (h:mm:ss or m:ss): `.

**Comment by alexdobin** [comment]
Hi Daniel,

thanks a lot for these tests. The results for ubuntu all look good. The RAM in this case will scale pretty much linearly with number of threads, since you are reserving huge chunks of RAM for each thread (~1.5GB per thread).

I guess it shows the danger of using static executables with older OS versions. I have to think if there is a workaround for that (apart, of course, from installing newer glibc).

I think this particular problem can be solved in a different way. I think I can modify the alogrithm so that this huge memory is not required. We do not really need to store all the ~1M of the transcripts, since we are only reporting the top few. Could you send me an example of a read mapping to IGH locus where --alignTranscriptsPerReadNmax 1000000 made a lot of difference?

Cheers
Alex

**Comment by ndaniel** [comment]
Hi Alex,

thanks for looking into this.
After all these it looks like this is due to running that static executable on *very old release* of CentOS (that is 5.1 where STAR is not even able to compile to begin with). It looks like on more up-to-date distros this is not an issue and therefore the workaround here is to use more up-to-date distro. Therefore I will close this issue and if in the future comes up again I will re-open it.

> 
Could you send me an example of a read mapping to IGH locus where --alignTranscriptsPerReadNmax 1000000 made a lot of difference?

I will be able to build a simulated data case for the data but this will take some time. Shortly, this is about fusion genes which involve IGH loci, where most of the time is a random insert in the fusion junction (i.e. fusion sequence looks like DNAseqIGHgene--5to8bpRandomInsert--DNAseqFromSomeNonIGHgeneLikeForExampleMYC). As far as I have seen STAR cannot align directly a read directly on genes DNAseqIGHgene and DNAseqFromSomeNonIGgeneLikeForExampleMYC with the random insert 5to8bpRandomInsert. In order to go around this I split a read into pieces, which are basically paired-end read and try to align that using ``--alignTranscriptsPerReadNmax 1000000`.
