### ISSUE TITLE
What is the advantage of  running STARsolo on Smartseq2 data compared to running traditional STAR+featureCounts on Smartseq2 data one by one ?

### ISSUE THREAD

**Issue by ahy1221** [alexdobin/STAR#1016]
Hi, 
It is happy to see new features related to Smartseq2 data added into STAR. 
I was wondering that what is the motivation and advantage to develop this feature and I am considering whether it is necessary to switch my pipeline to the new algorithm 

Thank you
Best,
Yao He

**Comment by HannahVMeyer** [comment]
Hi Alex, do you have an update on that question? I'd be curious too. Particularly with regards to the automatic filtering, that we only get when using STARsolo as opposed the STAR+featureCounts. The filtering seems more intuitive for the 10x based experiments to me, so any hints here would be great! Thanks

**Comment by alexdobin** [comment]
Hi Hannah,

I recall answering this question... but apparently, I did not. :) Sorry about that, Yao.
There are a couple of advantages I can think of:
1. The read-to-gene assignment policy for ```--soloType SmartSeq``` is the same that is used form Droplet-based technologies: only alignments that are completely concordant with transcript from exactly one gene are counted. featureCounts uses a different policy: any alignment that overlaps exons of a single gene is counted.
Since scRNA-seq typically have large % of intronic reads, it may affect the results significantly.

2. It is more efficient to run one STAR job with multiple fastq specified in the manifest files, compared to one-by-one runs:
https://github.com/alexdobin/STAR/discussions/1185#discussioncomment-538180

Cheers
Alex

**Comment by HannahVMeyer** [comment]
Thanks, Alex, that's great!

**Comment by ahy1221** [comment]
Thanks, Alex.   Then I will close this issue
