### ISSUE TITLE
outReadsUnmapped

### ISSUE THREAD

**Issue by francicco** [alexdobin/STAR#110]
Hi,

I'd like to get not aligned reads with "--outReadsUnmapped fastq" or "--outReadsUnmapped fastx" but I got to output nor errors.

How is the correct use for this option?

thanks
F

**Comment by alexdobin** [comment]
Hi Francesco,

you need to type precisely --outReadsUnmapped Fastx.
If this does not work, please send me your Log.out file.

Cheers
Alex

**Comment by soungalo** [comment]
This is a bit of a strange behavior. Since 'Fastx' is the only possible value other than None, I think it'd make more sense to simply remove this part and make this a flag argument, so the user would just have to pass '--outReadsUnmapped'. Alternatively, please make the documentation more clear and add an assertion for the value. For example, I tried passing '--outReadsUnmapped Fastq' and the software just ignored it (no output and no error), which is a bit confusing.
Thanks!

**Comment by alexdobin** [comment]
Hi Lior,

thanks for your suggestions. I prefer to use options rather than flags, since I may add more options in the future, but I will add assertion for this option.

Cheers
Alex
