### ISSUE TITLE
comparison of unsigned x >= negative constants

### ISSUE THREAD

**Issue by smoe** [alexdobin/STAR#114]
<pre>
g++ -c -Wdate-time -D_FORTIFY_SOURCE=2  -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Tue Feb 23 19:09:28 CET 2016 :/home/moeller/git/debian-med/rna-star/source"' -flto -flto -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D'COMPILATION_TIME_PLACE="Tue Feb 23 19:09:28 CET 2016 :/home/moeller/git/debian-med/rna-star/source"' ReadAlign_alignBAM.cpp
ReadAlign_alignBAM.cpp: In instantiation of ‘int bamAttrArrayWriteInt(intType, const char*, char*, Parameters*) [with intType = long long unsigned int]’:
ReadAlign_alignBAM.cpp:212:76:   required from here
</pre>
At this position is the invocation of bamAttrArrayWriteInt on the nMM attribute of a Transcript (trOut). The attribute is defined in Transcript.h as "uint nMM;//max number of mismatches". The warning then manifests itself in the implementation of bamAttrArrayWrite:
<pre>
ReadAlign_alignBAM.cpp:92:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (x >= -127) {
               ^
ReadAlign_alignBAM.cpp:94:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         } else if (x >= -32767) {
                      ^
ReadAlign_alignBAM.cpp:98:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (!(x>=-2147483647)) {
                    ^
</pre>
Stackoverflow has some idea to specialise the template 
http://stackoverflow.com/questions/4762110/partial-template-specialization-based-on-signed-ness-of-integer-type
I admit that the issue looks rather harmless at a second sight, depending on what size the nMM could possibly take. Nonetheless, please find a way to avoid that warning. I shall find a patch myself if you give me some constraints on what kind of solution you would feel prepared to accept.

**Comment by alexdobin** [comment]
Hi Steffen,

thanks for pointing this out. 
I think it was harmless since before the comparisons to negative numbers will never happen for unsigned int since they require neagtive number to begin with (x<0 condition). Still, it's better to get rid of the warnings - I have solved it by simply casting the variable to signed int64, which should be safe unless its bigger than 2^63.
I liked the enable_if solution from your link, but I would have to have another copyof the template just for unsigned variable that would deny the purpose of having the template.

Cheers
Alex
