### ISSUE TITLE
Lost splice junctions in multi-mapping relative to first pass 

### ISSUE THREAD

**Issue by aldriche-22** [alexdobin/STAR#1150]
Hi @alexdobin, 

I’m working on an RNA sequencing project with multi-mapping, and it seems from the contents of our SJ.out.tab files that we’ve lost a lot of splice junctions between STAR first pass and multi-mapping: from 8,363,743 introns detected in the first pass, our multi-mapping SJ.out.tab files contain a total of 8,359,972 introns. Is this behavior expected, to lose splice junctions on the second pass relative to the first pass? 

Thank you for your help!

**Comment by alexdobin** [comment]
Hi @aldriche-22 

are you counting the number of lines in the SJ.out.tab, or total number of counts in the SJ.out.tab, i.e. summing column 8 (unique mappers) or 9 (multimappers)?

For the former (i.e. number of introns regardless how many reads map to them), it is possible that this number is reduced after the 2nd pass, i.e. some of the introns are not detected anymore. This happens because the reads that map to these junctions in the 1st pass, are no longer mapping there in the 2nd pass - they find a "better" alignment to junctions detected in the 1st pass. I expect the introns that disappears should be mostly non-canonical (check column 5).

On the other hand, the total number of reads crossing the junctions should practically always increase in the 2nd pass.

Cheers
Alex

**Comment by aldriche-22** [comment]
@alexdobin, 

We're counting the number of lines in the SJ.out.tab files. This was really helpful for us moving forward, thank you for your help!

Thanks for writing such a great package!
