### ISSUE TITLE
Spurious uniquely mapping reads

### ISSUE THREAD

**Issue by red-plant** [alexdobin/STAR#1191]
Dear Dr. Dobin and STAR team members,

Why does STAR report reads as uniquely mapping when they are mapped to sequence that exist 2 times in my genome with no differences?

I used the following flags for the allele-specific run, using STAR 2.7.8a:

--winBinNbits 11
--outFilterMultimapNmax 1
--outFilterMultimapScoreRange 0
--sjdbFileChrStartEnd $sjdbFile

I am mapping reads against a diploid genome with a diploid annotation generated from the maize reference B73 V5 and a VCF file I made, including SNPs and indels. I think STAR should report only reads that overlap variants between each genome given the parameters used, however, I found only ~60% of them actually overlap variants. The remaining ~40% does not overlap any variant but STAR still reports them as uniquely mapping reads. Is this the intended behavior? Am I doing something wrong? 
I had posted this a few years ago but I think my question was not clear then and I closed the issue since I found a work-around.
Also, are you planning on enabling including indels for WASP runs or genomes generated using the genomeTransform options?
Any guidance would be greatly appreciated. Thanks.

Best,
José

**Comment by red-plant** [comment]
Hi,

I extracted 100 of the reads that were reported as uniquely aligned but did not overlap variants. I'm attaching the fastq file with these 100 reads, and the bam file and the logs from STAR that I got when running them again. Only 1 of them now overlaps variants, because the run was a bit different, but anyway. 
I think with this and the VCF file the problem should be completely reproducible. Which I can share if needed.

Best,
José

[STAR.test.folder.zip](https://github.com/alexdobin/STAR/files/6239002/STAR.test.folder.zip)

**Comment by alexdobin** [comment]
Hi José

I would recommend the following to debug this issue.
Create a diploid genome without any variants (identical haplotypes) and map these reads to such a genome.
If you see some of them mapping uniquely, it would indicate a problem with STAR alignments.

Cheers
Alex

**Comment by red-plant** [comment]
Hi, Dr. Dobin

Sorry for the delay. I tried to do as you recommended, but the index generation step gets stuck at "sorting Suffix Array chunks and saving them to disk", I ran it with 20 threads for like 3 hours, then I used only one chromosome and ran it over-night in my laptop and still nothing. I am guessing STAR might have problems sorting identical sequences? The index was build in ~1H when the differences were inserted in the genome in my laptop. Could you please advice me on how to proceed? 

Thanks
José

**Comment by alexdobin** [comment]
Hi José

you are right, you would need to use --genomeSuffixLengthMax 300 (or even smaller, = read length) to speed up index generation for identical sequences. I forgot about it... sorry about that.

Cheers
Alex

**Comment by Scy-bio** [comment]
Dear Dr. Dobin,  

I have some same problems about it. 
I want to anlysis the allele-specific-expression,so first i builded the Parental genome  by replace the snp sites respectively  in the reference genome，then use the  "cat" command  to get a diploid pseudogenome.
second，i use this fasta files and reference gtf file (just replace the snps, so i think the gtf file don't need rebuild) to generate genome indexes files, here is my code:
`
STAR --genomeSAindexNbases 13 --runThreadN 20 --runMode genomeGenerate \  
--genomeDir Diploid_index_dir --genomeFastaFiles genome_Diploid \  
--sjdbGTFfile $ref.gtf --sjdbOverhang 149`

After that, i mapped reads to the genome using the following code:
`
STAR --genomeDir Diploid_index_dir  --runThreadN 20     \  
           --readFilesIn R1.fastq.gz R2.fastq.gz --readFilesCommand zcat  \  
          --outFileNamePrefix  tmp  --outFilterMultimapNmax 1 --outFilterMismatchNmax 0   \  
          --outSAMtype BAM SortedByCoordinate  --outBAMsortingThreadN 10    \  
--outFilterIntronMotifs RemoveNoncanonicalUnannotated
`

If it's the same as I expected，the result sorted_bam file is only contains uniquely mapping reads, but here i have two question,
first ,because i use same chromosome name in my Parental genome, so the bam file has duplicate header. And when i want to use samtool to view my bam file , it has wrong:

`**Duplicate entry "<chromosome name>" in target list**`

Do you have any solution? The solution I can think of is to change the parameter "--outSAMtype" to ‘sam’ format
and the  athor question is, like you say, i created a diploid genome without any variants (identical haplotypes) and map the reads to such a genome.Here is my code:
> **created a diploid genome**
cat $ref.genome $ref.genome > genome_Diploid_S

> **generate genome indexes**
nohup STAR --genomeSAindexNbases 13 --runThreadN 20 --runMode genomeGenerate \   
                     --genomeDir Diploid_index_dir_S --genomeFastaFiles genome_Diploid_S \  
                    --sjdbGTFfile $ref.gtf --sjdbOverhang 149 --genomeSuffixLengthMax 300 

> **mapping** 
STAR --genomeDir Diploid_index_dir_S  --runThreadN 20     \  
           --readFilesIn R1.cleaned.fastq.gz R2.cleaned.fastq.gz --readFilesCommand zcat  \  
          --outFileNamePrefix  tmp_S  --outFilterMultimapNmax 1 --outFilterMismatchNmax 0   \  
          --outSAMtype BAM SortedByCoordinate  --outBAMsortingThreadN 10   \  
          --outFilterIntronMotifs RemoveNoncanonicalUnannotated


although it is not completed，i have some progress.out record:
>Read     Read   Mapped   Mapped   Mapped   Mapped Unmapped Unmapped Unmapped Unmapped  
  number   length   unique   length   MMrate    multi   multi+       MM    short    other
  1.5       86848      299    15.2%    253.6     0.0%     0.0%    19.8%     0.0%    64.7%     0.3%
  22.1     1642350      299    21.5%    261.9     0.0%     0.0%    25.6%     0.0%    52.7%     0.3%
  27.4     2592526      299    21.9%    262.2     0.0%     0.0%    26.0%     0.0%    51.8%     0.3%
  27.6     3110664      299    22.2%    262.4     0.0%     0.0%    26.3%     0.0%    51.3%     0.3%

as you can see i got some Mapped unique reads, do you have any good suggestion?

Best,
Yu

**Comment by red-plant** [comment]
Hi @Scy-bio,

I would recommend to rename your files so you do not have duplicate chromosome names in your fasta files nor duplicate gene names in your annotation files. If you wish to perform allele-specific expression you will need to do this anyway, otherwise you will not be able to tell which chromosome/gene your reads align to. 
The easiest way to do this is probably adding the following flags when generating your genome index with STAR:
` --genomeTransformType Diploid --genomeTransformVCF $VCF `
This will tag the chromosome names appending _h1 and _h2 in your alignment files.
Alternatively, since you are using only SNPs, I believe you could use
`--varVCFfile $VCF`
At the alignment step with your normally generated index. See section 10 of STAR manual "Detection of personal variants overlapping alignments."

As for the reads mapping uniquely in your homodiploid genome, I do not know why is that happening but I could not get any when I did the same with my files. I did re-named chromosomes (with identical sequences) and had a diploid annotation also re-named. 

Best,
José

**Comment by Scy-bio** [comment]
Hi @red-plant,

Thank you for very useful recommendations，and i will try to implement them soon.
Here i have other small question.
As i see your another issue ([Uniquely mapping reads to identical regions](https://github.com/alexdobin/STAR/issues/582) ), after getting the unique reads, you just using featureCounts for counting the gene expression. It seems more convenient and accurate when compare with some tools count the gene expression by using the SNPs(like GATK ASEReadCounter).Do you have any related published articles，or any ideas about this two counting pipeline?

Best,
Yu

**Comment by red-plant** [comment]
Dear Dr. Dobin,

I found that my scripts where the ones not handling complex variants adequately, I am sorry I took your time. Now 95% of my uniquely aligned reads overlap with variants. Thanks for developing STAR.

Best,
José



Hi @Scy-bio,

featureCounts can actually count the reads aligned to variants instead of genes, actually, it will count reads aligned to any set of coordinates you tell it to, so I just fed it with the coordinates of the variants instead of the coordinates of the genes. I have not tried any specialized variant counter, I find them overly complicated. I think both strategies will give you almost identical results (if you do not mess up like I did). I am closing this issue to avoid further spamming Dr. Dobin.

Wish you the best with your projects,
José
