### ISSUE TITLE
STARSolo input with BAM (usage)

### ISSUE THREAD

**Issue by cnk113** [alexdobin/STAR#1213]
Hello,

I was wondering when you input a BAM file for STARSolo, will the information to remap be at UMI resolution?
I have a custom dataset where the CB+UMI is tagged for internal reads which I then merged with a 3' end library that also has the CB+UMI (both libraries are from the same CB+UMI RNA library). The problem I have is that for any specific CB+UMI I have multiple different read pairs spanning the transcript. My question is would STARSolo be able to remap all the different reads (grouped by UMI) to the most likely transcript? Pretty much I have a fragmented (missing a few bases here and there) isoform library at single molecule resolution.

The alternative I was thinking of doing is something like a "mega-read" at the fastq level, but I believe the STAR aligner takes into account the splice junctions which my "mega-reads" wouldn't follow since there is a bit of dropout.

Thanks,
Chang

**Comment by alexdobin** [comment]
Hi Chang,

if you input reads to STARsolo from BAM, it simply takes the CB/UMI sequences from the SAM tags, instead of barcode read FASTQ. All the processing of CB/UMIs is exactly the same as for FASTQ input.

If you have two different libraries, it's probably better to process them separately, and then combine the resulting files.
For each CB/UMI combinations, STAR will "collapse" (i.e. count once) reads that map to the transcripts of the same gene.

Cheers
Alex

**Comment by cnk113** [comment]
Hey Alex,

Thanks for the reply. I should clarify these are the two libraries from the same pool of RNA, just processed and amplified differently. Is there perhaps a setting to also attempt mapping to the most likely transcript of a gene?

Thanks,
Chang

**Comment by alexdobin** [comment]
Hi Chang,

presently, STARsolo does not assign UMI to a specific transcript - rather, it assigns UMI to a gene.
We are working on a more sophisticated algorithm for transcript quantification, but it's still a few months out.

Cheers
Alex
