### ISSUE TITLE
STARsolo: An issue of --clipAdapterType

### ISSUE THREAD

**Issue by alanlamsiu** [alexdobin/STAR#1217]
Hi Alex,

In the parameter "--clipAdapterType", it metions that "5p and 3p adapter clipping similar to CellRanger4" when "CellRanger4" is specified. Is there a way to specify the adapter sequence for clipping. In our data, we found that the TSO sequence frequently occurs in the 5' end of read 2.

Thanks!

Xiao

**Comment by alexdobin** [comment]
Hi Xiao,

presently, only CR4 TSO sequence is hardcoded for 5' adapter.
I have it on my TODO list to allow an arbitrary 5' adapter sequence clipping.

Cheers
Alex

**Comment by alanlamsiu** [comment]
Hi Alex,

Thanks for the reply and good to know about the upcoming functions!

In addition, I would also like to mention about the read trimming functions in STAR. Is it also possible to hard trim the reads to specified lengths, different for read 1 and 2. I am bringing this up because for single-cell RNA-seq data, it is common to sequence reads longer the the barcodes or optimal size of the cDNAs. So it would be nice if STAR can integrate a trimming step based on the read length.

Thanks.
Xiao

**Comment by alexdobin** [comment]
Hi Xiao,

you can trim read 5' and 3' ends by a specified number of bases with
*--clip5pNbases* and *--clip3pNbases*.
For instance, *--clip3pNbases 20 10* will clip 20 bases from 3' of the 1st mate and 10b from the 2nd mate. The order of mates is as specified in *--readFilesIn*.

You do not need to trim the barcode read, but if its length is larger than CB+UMI length, you need to use *--soloBarcodeReadLength 0* so that STAR does not throw an error.

Cheers
Alex

**Comment by alanlamsiu** [comment]
Hi Alex,

Thanks for the explanation. It's all clear now.

Thanks.
Xiao
