### ISSUE TITLE
limitGenomeGenerateRAM errors

### ISSUE THREAD

**Issue by aLahat** [alexdobin/STAR#129]
when I run this:
```
STAR --runThreadN 8 --runMode genomeGenerate --genomeDir genome/index/ --genomeFastaFiles genome/Homo_sapiens.GRCh38.dna.toplevel.fa --sjdbGTFfile genome/Homo_sapiens.GRCh38.84.gtf --sjdbOverhang 79
```
I get:
```
STAR
Apr 01 14:43:41 ..... Started STAR run
Apr 01 14:43:41 ... Starting to generate Genome files

EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify limitGenomeGenerateRAM not less than124544990592 and make that much RAM available 
```
I also cannot add 
`--limitGenomeGenerateRAM 124544990592`
as it gives me an error that there is no such option.

**Comment by alexdobin** [comment]
Hi Albert,

how big is your genome? Since STAR requests 124GB, it should be ~14 gigabases?
--limitGenomeGenerateRAM command should work - please check the spelling and send me the Log.out file.

Cheers
Alex

**Comment by aLahat** [comment]
hi.

IT was human genome. but its solved now.
Was using: 
 --limitGenomeGenerateRAM `124544990592` 
instead of:
 `--limitGenomeGenerateRAM=124544990592`

**Comment by huangwb8** [comment]
@alexdobin Hi~
I also met similar problem like aLahat. I set `--limitGenomeGenerateRAM 171798691840` (I have to do that), but there are only 64G RAM of my server. Now I'm running STAR, but it's very slow to index the genome. Is it possible for me to index tremendous genome (~60G of .fa) in my tiny server?  If it's theoratically impossible, I gonna to stop it because it occupied all of my RAM.
Thanks!

**Comment by alexdobin** [comment]
Hi Weibin,

no, unfortunately such a large genome (~60 Gbases) requires much larger RAM, I would recommend no less than 256GB.

Cheers
Alex

**Comment by huangwb8** [comment]
Thanks! I had turn to a smaller genome. Everything is OK!

**Comment by ACIITB23** [comment]
Hi @alexdobin,
 
I have 32GB RAM in my system and working on human genome, I am also getting the same kind error, Please help me to fix it.
Thank you!

Command using:

`STAR --runThreadN 16  --runMode genomeGenerate --genomeDir /home/bioinfosunlab/Documents/scRNA_tutorial_TEST/GenomeIndex/DB --genomeFastaFiles gencode.v38.transcripts.fa --sjdbGTFfile hg38.refGene.gtf --sjdbOverhang 99 --limitGenomeGenerateRAM 32000000000`

Error getting:

`STAR version: 2.7.11b   compiled: 2024-01-25T16:12:02-05:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Jun 12 15:26:51 ..... started STAR run
Jun 12 15:26:51 ... starting to generate Genome files`

`EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=32000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 165684095925 and make that much RAM available `

`Jun 12 15:26:52 ...... FATAL ERROR, exiting`
