### ISSUE TITLE
the way to align using different read length

### ISSUE THREAD

**Issue by dahun73** [alexdobin/STAR#1298]
Hi Alex :)

I just have a question about different length.

Briefly speaking, R2 reads have UMIs. So, I processed UMIs the first 5 sequences of R2. As a result, R1 and R2 length are different(R1 is 76bp and R2 is 71bp). In this case....Is there any suggestion...?

Always thank you :)

Dahun

**Comment by alexdobin** [comment]
Hi Dahun,

I am not sure I completely understand the question. 
Are you mapping PE reads were one read is 76b and the other is 71b after trimming.
This is not problem, no need to adjust parameters.

Cheers
Alex

**Comment by dahun73** [comment]
Hello Alex!

thank you for reply. Yes, you are right…  My trimmed fastq files were broken during trimming…haha…

Can I ask you two more questions?
Looking at the log file, there are many information about alignment. Such as bowtie2, can we check out cocordant or discordant read percentage? I’m confused about terms for quality check.

Second question is regarding BAM file composition. We can check final log file after alignment. Only uniquely mapped reads are included in BAM files, right..? If not, other reads such as multiple mapped reads and unmapped reads are included in BAM file?
The reason why I ask this question is that I can find the number of unmapped reads when I use “samtools view -cf 4 [bam]”.

I have analyzed all data not to understand such as basic knowledge….TT

always thanks Alex :)


Dahun

**Comment by alexdobin** [comment]
Hi Dahun,

STAR has a strong preference for concordant alignments.
For mates of equal length, with default parameters only concordant alignment are output.
However, since you reads are trimmed, you may see some single-end alignments (of one of the mates was trimmed much more than the other).

To check for non-concordant reads you can use ```samtools flagstat``` command, though it will count all multimapping alignments: by default, STAR will output unique and multi-mappers.
You can select the unique mappers only with ```samtools view -q 255``.

Cheers
Alex

**Comment by dahun73** [comment]
Thank you so much Alex :)

So, I tried to calculate and reproduce uniquely mapped reads of Log file. However, it is hard to reproduce.....

in Log file:
                          Number of input reads |	7589317
                      Average input read length |	147
                                    UNIQUE READS:
                   Uniquely mapped reads number |	1839713
                        Uniquely mapped reads % |	24.24%

I used "samtools flagstat". The result is :
3911728 + 0 in total (QC-passed reads + QC-failed reads)
155310 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
3911728 + 0 mapped (100.00% : N/A)
3756418 + 0 paired in sequencing
1878209 + 0 read1
1878209 + 0 read2
3756418 + 0 properly paired (100.00% : N/A)
3756418 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

I also used "samtools -cF 0x904 [*.bam]".
The result is 3756418

How can I reproduce the number of uniquely mapped reads...?


Thank you in advance
Dahun

**Comment by alexdobin** [comment]
Hi Dahun,

Roughly, the number from samtools is ~2 * UniqueMappNumber (because samtools counts each end of the read).
The exact agreement is not possible since for some of the reads only one end is mapped.
To reproduce the UniqueMappedNumber you need to count the number of unique read IDs for uniquely mapping reads, something like:
```samtools view -q 255 A.bam | cut -f1 | sort -u | wc```

Cheers
Alex
