### ISSUE TITLE
Alignment allows specific nucleotide transition

### ISSUE THREAD

**Issue by Codezy99** [alexdobin/STAR#1429]
Dear Alexdobin,

I am working on a SLAM-seq data which use to measure the stability of RNA transcripts. This method calculates the transcripts' half life with the T to C transition which cause by the 4sU labeling. I was wondering if we can allows more T to C mismatches for the alignment with STAR? Thank you!

Best regards,
You

**Comment by alexdobin** [comment]
Hi You,

there is no option to selectively favor mismatched bases.
If you have a large number of T->C switches in each read, the best option is probably to reduce the alphabet to 3 bases, similar to what's done for the bisulfite sequencing.

Cheers
Alex

**Comment by Codezy99** [comment]
Hi Alex,

I think we can not do that. Because we identify the newly generated reads based on this T -> C switch, and this will be used for the half life measuring. I will probably try to increase threshold for mismatch then. Thanks for your quick answer and happy new year : )

Cheers,
You

**Comment by alexdobin** [comment]
Hi  You,

in the alphabet reduction scheme, you replace all T into C (in reads and reference) just for the mapping step. Then, given the alignments, you can recalculate the number of T->C switches using the original read sequences and original genome sequence. This sequence allows mapping reads with a large %  (>~5%) of T->C mismatches, which otherwise will not be mapped.

Cheers
Alex

**Comment by Codezy99** [comment]
Hi Alex,

thanks very much for the clear explanation! That is a really good method to go. I will try it out : )

Cheers,
You
