### ISSUE TITLE
STARsolo not matching CellRanger output

### ISSUE THREAD

**Issue by sjroth** [alexdobin/STAR#1457]
I am using STARsolo on publicly available 10x V3 data (example accession here: https://www.ncbi.nlm.nih.gov/sra?term=SRX9708219 ). The reads are paired-end at 150 bp each The output is highly irregular and does not match CellRanger 6.1.2 on the same data. Of note, STARsolo is not detecting any cells.

Here is how I generated the genome index (where genome.fa and genes.gtf are from CellRanger's reference):
```
STAR --runMode genomeGenerate --runThreadN 16 --genomeDir genome_idx --genomeFastaFiles genome.fa --sjdbGTFfile genes.gtf --genomeSAsparseD 3
```

Here is the alignment/quantification command:
```
STAR --genomeDir genome_idx/ --readFilesIn SRR13278442_2.fastq SRR13278442_1.fastq --soloType CB_UMI_Simple --soloCBwhitelist 10x-v3-barcodes.txt --soloUMIlen 12 --soloCBlen 16 --soloUMIstart 17 --soloCBstart 1 --soloBarcodeReadLength 0 --clipAdapterType CellRanger4 --outFilterScoreMin 30 --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_CR --outSAMtype BAM Unsorted --runThreadN 16 --outFileNamePrefix test --soloCellFilter EmptyDrops_CR --soloFeatures GeneFull
```

This is the summary file output from STARsolo:
```
Number of Reads,131343810
Reads With Valid Barcodes,0.981454
Sequencing Saturation,-nan
Q30 Bases in CB+UMI,0.951324
Q30 Bases in RNA read,0.901431
Reads Mapped to Genome: Unique+Multiple,0.925342
Reads Mapped to Genome: Unique,0.850182
Reads Mapped to GeneFull: Unique+Multiple GeneFull,0
Reads Mapped to GeneFull: Unique GeneFull,0
Estimated Number of Cells,0
Unique Reads in Cells Mapped to GeneFull,0
Fraction of Unique Reads in Cells,-nan
Mean Reads per Cell,0
Median Reads per Cell,0
UMIs in Cells,0
Mean UMI per Cell,0
Median UMI per Cell,0
Mean GeneFull per Cell,0
Median GeneFull per Cell,0
Total GeneFull Detected,0
```

This is the summary output from CellRanger:
```
Estimated Number of Cells,Mean Reads per Cell,Median Genes per Cell,Number of Reads,Valid Barcodes,Sequencing Saturation,Q30 Bases in Barcode,Q30 Bases in RNA Read,Q30 Bases in UMI,Reads Mapped to Genome,Reads Mapped Confidently to Genome,Reads Mapped Confidently to Intergenic Regions,Reads Mapped Confidently to Intronic Regions,Reads Mapped Confidently to Exonic Regions,Reads Mapped Confidently to Transcriptome,Reads Mapped Antisense to Gene,Fraction Reads in Cells,Total Genes Detected,Median UMI Counts per Cell
"22,866","5,744",307,"131,343,810",97.7%,51.6%,95.2%,90.6%,95.0%,92.5%,85.4%,4.7%,55.2%,25.5%,22.8%,1.1%,78.1%,"23,815",397
```

Please advise.

**Comment by alexdobin** [comment]
Hi @sjroth 

the 10X barcodes are detected fine, but the issue is that STAR is not assigning any reads to any genes.
What is the output in the GeneFull/Features.stats?
Where did you get the genome.fa and genes.gtf file?
Please send me Log.out files for the genome generation and mapping.

Cheers
Alex

**Comment by sjroth** [comment]
Hi @alexdobin,

Do you have any suggestions?

**Comment by alexdobin** [comment]
Hi @sjroth 

I mapped this library (just 1M reads) to a genome generated with 10X-3.0.0 human fasta/gtf, and there seems to be no problem (see below).
fastq-dump --split-files create 3 fastq files with _1 index read we do not need, so I had to do:
```--readFilesIn SRR13278442_3.fastq SRR13278442_2.fastq```
Otherwise, I used your parameters. So my guess is that the genome generation went wrong somehow.
Could you please send me the Log.out file for the genome generation?

Cheers
Alex

Summary.csv
Number of Reads,1000000
Reads With Valid Barcodes,0.975578
Sequencing Saturation,0.13166
Q30 Bases in CB+UMI,0.954964
Q30 Bases in RNA read,0.92044
Reads Mapped to Genome: Unique+Multiple,0.93296
Reads Mapped to Genome: Unique,0.857363
Reads Mapped to GeneFull: Unique+Multipe GeneFull,0.781294
Reads Mapped to GeneFull: Unique GeneFull,0.705469
Estimated Number of Cells,20614
Unique Reads in Cells Mapped to GeneFull,549596
Fraction of Unique Reads in Cells,0.779051
Mean Reads per Cell,26
Median Reads per Cell,22
UMIs in Cells,476561
Mean UMI per Cell,23
Median UMI per Cell,19
Mean GeneFull per Cell,22
Median GeneFull per Cell,19
Total GeneFull Detected,15694

**Comment by sjroth** [comment]
I did not do the --split-files! Let me give that a go and see if that works. Thank you!!!

**Comment by sjroth** [comment]
I was able to reproduce your output by using the correct fastq files. I am closing this thread.
