### ISSUE TITLE
STAR 2pass fails if directory not present

### ISSUE THREAD

**Issue by colindaven** [alexdobin/STAR#15]
Hi Alex,

quite impressed with STAR 2 pass finding ~25% extra splice sites on one sample compared to STAR.
 
One potential bug is that STAR2pass fails if the directory is not created in advance (even if --outFileNamePrefix is set). 

It starts fine if I create the directory in advance (see bottom)

Version: STAR_2.4.0h

## 1

STAR --genomeDir MA/star/ --twopass1readsN 500000000 --sjdbOverhang 99 --outFileNamePrefix M-P --alignIntronMax 150000 --runThreadN 12 --outFilterIntronMotifs RemoveNoncanonical  --readFilesIn ../../M-P_comb_R1.fastq ../../M-P_comb_R2.fastq

EXITING because of fatal ERROR: could not make pass1 directory: M-P/_STARpass1/
SOLUTION: please check the path and writing permissions 

Dec 22 14:34:08 ...... FATAL ERROR, exiting

## 2

mkdir M-P

STAR --genomeDir MA/star/ --twopass1readsN 500000000 --sjdbOverhang 99 --outFileNamePrefix M-P --alignIntronMax 150000 --runThreadN 12 --outFilterIntronMotifs RemoveNoncanonical  --readFilesIn ../../M-P_comb_R1.fastq ../../M-P_comb_R2.fastq
Dec 22 14:37:21 ..... Started STAR run

**Comment by alexdobin** [comment]
Hi Colin,

thanks for reporting this bug. I was adding "/" to the prefix, that's why it required M-P directory to be present, while you were asking for a simple prefix to the output file names. This is fixed now, please check the GitHub master.

Note that STAR requires the full path to the --outFileNamePrefix to exist before the run, even for the 1-pass run.

Cheers
Alex
