### ISSUE TITLE
--quantMode GeneCounts for paired-end

### ISSUE THREAD

**Issue by lldelisle** [alexdobin/STAR#1505]
Dear STAR developers,
I noticed that when I mapped a PE dataset (unstranded) with STAR version 2.7.8a, the pairs that have one mate mapped to a single gene and the other mate mapped to 2 genes (ambiguous) are considered as ambiguous.
I was wondering if this is something known and desired or if it is something that could change in future versions.
Thanks,
Lucille
PS: I have not checked htseq count behaviour.

**Comment by alexdobin** [comment]
Hi Lucille,

this is expected behavior: if one of the mates maps to multiple loci, the entire read will be considered a genomic multimapper.
STAR does not consider annotation status of the reads, so it cannot decide that the same-gene alignment is the correct one.
This has to be done in the post-mapping step.

Best,
Alex

**Comment by lldelisle** [comment]
Hi @alexdobin ,
Thanks for your clear answer.
