### ISSUE TITLE
Does "Column with most reads" principle applies to unstranded?

### ISSUE THREAD

**Issue by andrebolerbarros** [alexdobin/STAR#1589]
Hey,

Previously, there was an issue asking for how to determine if our files are stranded and unstranded, to which the answer was:

"Another (less visual) possibility is to run STAR with the --quantMode GeneCounts option, and count total read counts on genes in the 3 and 4 columns (these column represent different library strandedness). For stranded data one of the columns should be much larger than the other. You can use this to estimate strandedness of the data quantitatively." ([Issue #258](https://github.com/alexdobin/STAR/issues/258), already closed).

I was wondering if the same principle applies for unstranded data, ie, if I have more reads in the first column of the ReadsPerGene file, does that mean my data is unstranded?

**Comment by alexdobin** [comment]
Hi André

for the unstranded data, the counts in the 3rd and 4th columns should be approximately equal. For instance, you can make a scatter plot 3rd vs 4th column, and it should be scattered around y=x line.

For most genes, the unstranded column has larger counts than either 3rd or 4th column, even for stranded protocols, since no protocol is perfectly stranded.

**Comment by andrebolerbarros** [comment]
Thanks for the clear explanation!
