### ISSUE TITLE
BU??? doesn't work?

### ISSUE THREAD

**Issue by mehrdadsk** [alexdobin/STAR#1590]
Hi
I am creating DGE matrix. My read 1 file has 26 nucleotides. My barcodes length is 6 and UMI is 15, so I tried this command:

**java -jar BRBseqTools.jar CreateDGEMatrix -f Read1.fastq.gz -b BAM/Read2.bam -c Barcodes.txt -gtf genes.gtf -p BU????? -UMI 15**

But I get this error: zsh: no matches found: BU?????

Does anyone have any idea how can I solve it?

**Comment by YPHa** [comment]
Hi,

The question mark is being interpreted as a wildcard by your shell (like * but only for a single character).
I would advise putting it between single quotes:
-p 'BU?????'

Hope this helps.
________________________________
From: Mehrdad Shoae Kazemi ***@***.***>
Sent: Wednesday, June 22, 2022 2:52 PM
To: alexdobin/STAR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [alexdobin/STAR] BU??? doesn't work? (Issue #1590)


Hi
I am creating DGE matrix. My read 1 file has 26 nucleotides. My barcodes length is 6 and UMI is 15, so I tried this command:

java -jar BRBseqTools.jar CreateDGEMatrix -f Read1.fastq.gz -b BAM/Read2.bam -c Barcodes.txt -gtf genes.gtf -p BU????? -UMI 15

But I get this error: zsh: no matches found: BU?????

Does anyone have any idea how can I solve it?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falexdobin%2FSTAR%2Fissues%2F1590&data=05%7C01%7Cy.p.hagemeijer%40umcg.nl%7C2b337690d8294d7f5ced08da544e1bc3%7C335122f9d4f44d67a2fccd6dc20dde70%7C0%7C0%7C637914991689710572%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PUQqSPwwScUONSY0hERZXSO2kg5qqZZvjMZtj52%2FIcw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACBZ4EK4HRFP2E3H5574ZBLVQMEB5ANCNFSM5ZQDWOCA&data=05%7C01%7Cy.p.hagemeijer%40umcg.nl%7C2b337690d8294d7f5ced08da544e1bc3%7C335122f9d4f44d67a2fccd6dc20dde70%7C0%7C0%7C637914991689866784%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vZjmz%2Bxcd0QkoAyOf6iWXTiKeJdAho5cVfD1aLKUf3Y%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
De inhoud van dit bericht is vertrouwelijk en alleen bestemd voor de geadresseerde(n). Anderen dan de geadresseerde(n) mogen geen gebruik maken van dit bericht, het niet openbaar maken of op enige wijze verspreiden of vermenigvuldigen. Het UMCG kan niet aansprakelijk gesteld worden voor een incomplete aankomst of vertraging van dit verzonden bericht.

The contents of this message are confidential and only intended for the eyes of the addressee(s). Others than the addressee(s) are not allowed to use this message, to make it public or to distribute or multiply this message in any way. The UMCG cannot be held responsible for incomplete reception or delay of this transferred message.

**Comment by mehrdadsk** [comment]
Dear YPHa

Thank you for your nice solution. It is working now :)
