### ISSUE TITLE
Clarification on combining related --outFilter parameters and their default values

### ISSUE THREAD

**Issue by AlexBlais74** [alexdobin/STAR#1713]
Hello
I apologize for the long post with multiple questions, but they are all quite connected.

I have a few questions about STAR output filtering parameters that are related. For instance these two
```
--outFilterMatchNmin
default: 0
int: alignment will be output only if the number of matched bases is higher than or equal to this value.

--outFilterMatchNminOverLread
default: 0.66
real: sam as outFilterMatchNmin, but normalized to the read length (sum of mates’ lengths for paired-end reads)
```

**First question:** If I have two fastq file samples that come from different sequencing runs with different read lengths (e.g. 50bp or 100 bp reads), then using the defaults will align with different "stringency" (requiring either 33 or 66 reads to map correctly). I am getting that right?

**Second question:** maybe it's dumb to ask, but can it be confirmed that all --outFilter parameters are applied and combined in the "AND" fashion, even if they are not stated in the issued command (in which case they run at default values)?

**Third question:** when setting the value --outFilterMatchNminOverLread for local alignment, what value of read length is used? The length seen in the input fastq file, or the length that aligns well after soft-clipping? It seems logical that it would be the input read length, but I'd like an explicit confirmation of that. Also, I feel like this would have an influence on whether I trim my reads of low-quality sections BEFORE aligning with STAR (in which case the input reads are somewhat shortened) or if I let STAR handle the low-quality sections by soft-clipping.

Another example is with these two related parameters:
```
--outFilterMismatchNmax
default: 10
int: alignment will be output only if it has no more mismatches than this value.
--outFilterMismatchNoverLmax
default: 0.3
real: alignment will be output only if its ratio of mismatches to *mapped*
length is less than or equal to this value.
```

**Fourth and last question":** With reads of 50 bp, NoverLmax allows 15 mismatches, except that the Nmax parameter caps this to its 10 bp value by default. Is it correct then to conclude that because all filters are applied in the "AND" fashion, then the most stringent will prevail. So for reads of 50 the Nmax filter wins (10), but for reads of 30 bp it is the NoverLmax that prevails (9). I am asking because although nobody sequences at 30 bp anymore, there are still library prep technologies that require trimming of the 5' end of reads, e.g. with some UMI approaches, so short reads are still common.

Thank you so much for your time and maintaining a fantastic tool.

Alex

**Comment by alexdobin** [comment]
Hi Alex,

> First question: If I have two fastq file samples that come from different sequencing runs with different read lengths (e.g. 50bp or 100 bp reads), then using the defaults will align with different "stringency" (requiring either 33 or 66 ~~reads~~ bases to map correctly). I am getting that right?

Correct: min mapped length will be 33b for 50b reads and 66 bases for 100b reads.

> Second question: ~~maybe it's dumb to ask, but~~ can it be confirmed that all --outFilter parameters are applied and combined in the "AND" fashion, even if they are not stated in the issued command (in which case they run at default values)?

Correct!

> Third question: when setting the value --outFilterMatchNminOverLread for local alignment, what value of read length is used? The length seen in the input fastq file, or the length that aligns well after soft-clipping?
 It seems logical that it would be the input read length, but I'd like an explicit confirmation of that. Also, I feel like this would have an influence on whether I trim my reads of low-quality sections BEFORE aligning with STAR (in which case the input reads are somewhat shortened) or if I let STAR handle the low-quality sections by soft-clipping.

It will be the read length from the fastq file, unless you use STAR's adapter clipping options.
You are right - if you have large unmappable portions of reads, it's better to trim them before mapping, so that the min mapped length is normalized to the trimmed read length.
```--outFilterMismatchNoverReadLmax``` is also normalized to the read length, but ```--outFilterMismatchNoverLmax``` is normalized to mapped length (i.e. not including soft-clipped bases).

> Fourth and last question": With reads of 50 bp, NoverLmax allows 15 mismatches, except that the Nmax parameter caps this to its 10 bp value by default. Is it correct then to conclude that because all filters are applied in the "AND" fashion, then the most stringent will prevail. So for reads of 50 the Nmax filter wins (10), but for reads of 30 bp it is the NoverLmax that prevails (9). I am asking because although nobody sequences at 30 bp anymore, there are still library prep technologies that require trimming of the 5' end of reads, e.g. with some UMI approaches, so short reads are still common.

Correct! Note that these parameters allow a large number of mismatches by default, realying mostly on filtering by min mapped length and min alignment score (```--outFilterScoreMinOverLread```, ```--outFilterScoreMin```). If you need to restrict the number of mismatches, you will need to modify these parameters according to your liking.

**Comment by AlexBlais74** [comment]
Great. Thanks for the answers and the advice.
Alex
