### ISSUE TITLE
STAR --bamRemoveDuplicatesType UniqueIdentical vs PICARD MarkDuplicates

### ISSUE THREAD

**Issue by serge2016** [alexdobin/STAR#175]
Hello.
I have a BAM-file with sorted by coordinate transcriptome alignment (produced by STAR 2.5.2a). And I want to mark all duplicates (PCR, optical, ...). So I tested next cmds:
1. Picard cmd: java -Djava.io.tmpdir=$TMPDIR -jar $PICARD MarkDuplicates   I=$AlignRGSortFile   O=$AlignRGSortDedupFile1   CREATE_INDEX=true   VALIDATION_STRINGENCY=SILENT   METRICS_FILE=metrics.txt
2. STAR cmd: $STAR   --runThreadN $NUMCPUS   --limitBAMsortRAM 30000000000   --runMode inputAlignmentsFromBAM   --bamRemoveDuplicatesType UniqueIdentical   --inputBAMfile $AlignRGSortFile   --outFileNamePrefix $STARMarkDupDir/$sampleName.

To briefly check results I run samtools flagstat and see:
$ samtools flagstat SRR1609982.Aligned_STAR.rg.sorted.dedupped_picard.bam
89841696 + 0 in total (QC-passed reads + QC-failed reads)
13629240 + 0 secondary
0 + 0 supplementary
**16446046** + 0 duplicates
89841696 + 0 mapped (100.00% : N/A)
76212456 + 0 paired in sequencing
38106228 + 0 read1
38106228 + 0 read2
76212456 + 0 properly paired (100.00% : N/A)
76212456 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

$ samtools flagstat SRR1609982.Aligned_STAR.rg.sorted.dedupped_STAR.bam
89841696 + 0 in total (QC-passed reads + QC-failed reads)
13629240 + 0 secondary
0 + 0 supplementary
**31598600** + 0 duplicates
89841696 + 0 mapped (100.00% : N/A)
76212456 + 0 paired in sequencing
38106228 + 0 read1
38106228 + 0 read2
76212456 + 0 properly paired (100.00% : N/A)
76212456 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

STAR marked twice as many duplicates as picard! It seems to be incorrect...

**Comment by alexdobin** [comment]
Hi Sergey,

STAR marks all multimapping alignments as "duplicate". This was done for some compatibility with downstream ENCODE pipeline, and also because it's not clear how to call duplication on multimappers. This should explain most of the differences, since you have 13629240 secondary alignments.


Cheers
Alex

**Comment by serge2016** [comment]
Dear Alex,
Thank you for quick respond!
Is it possible to add some flag/option for STAR to mar or not mark secondary alignments as "duplicates"?

**Comment by alexdobin** [comment]
Hi Sergey,

yesm this should not be difficult, I will try to code this option tomorrow.

Cheers
Alex

**Comment by serge2016** [comment]
Dear Alex,

Thank you very much!
I have another question: could you point, please, the place with detailed description of what duplicate types are detected by STAR?
Here is the link to [Picard's description](http://broadinstitute.github.io/picard/command-line-overview.html#MarkDuplicates). There we can find that picard detects 2 types of duplicates (if I understand correctly): **PCR Duplicates** - arose during sample preparation e.g. library construction using PCR; and **Optical Duplicates** - from a single amplification cluster, incorrectly detected as multiple clusters by the optical sensor of the sequencing instrument.

**Comment by alexdobin** [comment]
Hi Sergey,

please try the latest github master with --bamRemoveDuplicatesType UniqueIdenticalNotMulti

STAR removes duplicates looking only at the alignment coordinates - i.e. reads that have the same start/end (soft-clippings are extended) and CIGARS for both mates. I am not sure how  one can differentiate PCR Duplicates from Optical Duplicates, but in both cases they should produce nearly identical sequences that should map to nearly identical loci.

Cheers
Alex

**Comment by serge2016** [comment]
Dear Alex,
Here is the result:
$ samtools flagstat SRR1609982.Aligned_STAR.rg.sorted.dedupped_STAR_2.5.2b.bam
89841696 + 0 in total (QC-passed reads + QC-failed reads)
13629240 + 0 secondary
0 + 0 supplementary
**8976280** + 0 duplicates
89841696 + 0 mapped (100.00% : N/A)
76212456 + 0 paired in sequencing
38106228 + 0 read1
38106228 + 0 read2
76212456 + 0 properly paired (100.00% : N/A)
76212456 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

Now STAR marked two times less reads than Picard...

**Comment by alexdobin** [comment]
Hi Sergey,

I digged a bit deeper into the discrepancies between the picard and STAR duplicate removal. The biggest difference is that with the new option STAR will not mark any multimappers as duplicates, or even use them to check duplicates for unique mappers. Picard seems to mark duplicates as multimappers. I am not sure what the rules are for multimappers - do you require that all multi-aligns for a read have a duplicate? or only one is enough? I think it's easier to stay away from multimappers.

Also, I have found some strange duplicates assignments by Picard for unique mappers which I cannot explain, e.g.:
SRR1609982.776867       163     1       22418625        255     101M    =       22418645        121     TAATAACATACTCCTTTTTGAAAGTTGCCTTTTCTCTCCACCCTTGAGTAGATCCAGTATTTGATGAAACTCATGAAAGTGGGTGGAGCCCATCTTGCCCC
SRR1609982.623915       163     1       22418638        255     101M    =       22418686        149     CTTTTTGAAAGTTGCCTTTTCTCTCCACCCTTGAGTAGATCCAGTATTTGATGAAACTCATGAAAGTGGGTGGAGCCCATCTTGCCCCTCCTCTTTTCTAG
SRR1609982.940823       1123    1       22418638        255     101M    =       22418686        149     CTTTTTGAAAATTGCCTTTTCTCTCCACCCTTGAGTAGATCCAGTATTTGATGAAACTCATGAAAGTGGGTGGAGCCCATCTTGCCCCTCCTCTTTTCTAG
SRR1609982.328988       163     1       22418641        255     101M    =       22418660        120     TTTGAAAGTTGCCTTTTCTCTCCACCCTTGAGTAGATCCAGTATTTGATGAAACTCATGAAAGTGGGTGGAGCCCATCTTGCCCCTCCTCTTTTCTAGGAC
--
SRR1609982.29345        83      1       22418661        255     101M    =       22418597        -165    TCCACCCTTGAGTAGATCCAGTATTTGATGAAACTCATGAAAGTGGGTGGAGCCCATCTTGCCCCTCCTCTTTTCTAGGACGCACTATATGTGACTGTGAC
SRR1609982.623915       83      1       22418686        255     101M    =       22418638        -149    TGATGAAACTCATGAAAGTGGGTGGAGCCCATCTTGCCCCTCCTCTTTTCTAGGACGCACTATATGTGACTGTGACTTTCAAGGACATTTGTTTGCCATTT
SRR1609982.940823       1171    1       22418686        255     101M    =       22418638        -149    TGATGAAACTCATGAAAGTGGGTGGAGCCCATCTTGCCCCTCCTCTTTTCTAGGACGCACTATATGTGACTGTGACTTTCAAGGACATTTGTTTGCCATTT
SRR1609982.984847       147     1       22418755        255     101M    =       22418542        -314    CTGTGACTTTCAAGGACATTTGTTTGCCATTTGCTGATTTTTTTGGGAAGTTAATTTCTAACTTCTTTCACTGATAAATGAAGAAAAGTATTGCACCTTTG

I guess Picard finds SRR1609982.623915 and SRR1609982.940823 to be duplicates, but it only marks the latter one. STAR does not mark them as duplicates because their flags are different - the represent the same fragment in a different orientation (i.e. read 1/2 swapped).

Cheers
Alex

**Comment by everestial** [comment]
How do you remove the duplicated later, if marked by STAR? which tag to be specific.

**Comment by alexdobin** [comment]
Hi @everestial 

sorry for belayed reply, I missed your question.
Duplicates are marked with 0x400 bit set in the FLAG, and can be removed with
$ samtools view -b -F 0x400 Aligned.markDupl.bam > Aligned.removeDupl.bam

Cheers
Alex
