### ISSUE TITLE
Fifo files cannot be created

### ISSUE THREAD

**Issue by Erikado4** [alexdobin/STAR#1776]
Hello,

I am trying to use STAR for the first time with the velocyto option, using the following command:

STAR --runThreadN 15 --genomeDir /mnt/c/Users/gilbe/Desktop/velocyto/index --genomeLoad NoSharedMemory --readFilesIn /mnt/g/fastq/Young_S7_L001_R1_001.fastq,/mnt/g/fastq/Young_S7_L002_R1_001.fastq /mnt/g/fastq/Young_S7_L001_R2_001.fastq,/mnt/g/fastq/Young_S7_L002_R2_001.fastq --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --soloType CB_UMI_Simple --soloCBstart 1 --soloUMIstart 17 --soloCBlen 16 --soloUMIlen 12 --soloBarcodeReadLength 1 --soloCBwhitelist 3M-february-2018.txt --soloStrand Forward --soloFeatures Gene Velocyto --soloUMIdedup 1MM_CR --soloCBmatchWLtype 1MM_multi_pseudocounts --soloCellFilter EmptyDrops_CR 15000 0.99 10.0 45000 90000 500 0.01 20000 0.01 10000 --soloUMIfiltering MultiGeneUMI_CR --soloOutFormatFeaturesGeneField3 "Gene Expression" --outFileNamePrefix /mnt/c/Users/gilbe/output/ --outTmpDir /mnt/c/Users/gilbe/output/tpm

I am on WSL/Ubuntu with conda installation of STAR.

And I get the following error which I don't have the expertise to address: 

Exiting because of *FATAL ERROR*: could not create FIFO file /mnt/c/Users/gilbe/output/tpm/tmp.fifo.read1
SOLUTION: check the if run directory supports FIFO files.
If run partition does not support FIFO (e.g. Windows partitions FAT, NTFS), re-run on a Linux partition, or point --outTmpDir to a Linux partition.

This error happens with both my compressed and uncompressed fastq files. I also tried change the thread number. 

Any chance someone can help me out?

**Comment by YPHa** [comment]
Dear Erikado4,

The error message seems to give clear advice on what to do:

Try to set the "--outTmpDir" parameter to a path that is not one of your windows partitions/harddisks (C, D, etc.). Instead try to store it somewhere outside of the "/mnt/", for example use "/tmp/" or create a dedicated directory in your ubuntu home directory.

Afterwards you can access those wsl paths from windows by typing "explorer.exe ." as a wsl command.


________________________________
From: Erikado4 ***@***.***>
Sent: Wednesday, March 1, 2023 10:19 PM
To: alexdobin/STAR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [alexdobin/STAR] Fifo files cannot be created (Issue #1776)


Hello,

I am trying to use STAR for the first time with the velocyto option, using the following command:

STAR --runThreadN 15 --genomeDir /mnt/c/Users/gilbe/Desktop/velocyto/index --genomeLoad NoSharedMemory --readFilesIn /mnt/g/fastq/Young_S7_L001_R1_001.fastq,/mnt/g/fastq/Young_S7_L002_R1_001.fastq /mnt/g/fastq/Young_S7_L001_R2_001.fastq,/mnt/g/fastq/Young_S7_L002_R2_001.fastq --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --soloType CB_UMI_Simple --soloCBstart 1 --soloUMIstart 17 --soloCBlen 16 --soloUMIlen 12 --soloBarcodeReadLength 1 --soloCBwhitelist 3M-february-2018.txt --soloStrand Forward --soloFeatures Gene Velocyto --soloUMIdedup 1MM_CR --soloCBmatchWLtype 1MM_multi_pseudocounts --soloCellFilter EmptyDrops_CR 15000 0.99 10.0 45000 90000 500 0.01 20000 0.01 10000 --soloUMIfiltering MultiGeneUMI_CR --soloOutFormatFeaturesGeneField3 "Gene Expression" --outFileNamePrefix /mnt/c/Users/gilbe/output/ --outTmpDir /mnt/c/Users/gilbe/output/tpm

I am on WSL/Ubuntu with conda installation of STAR.

And I get the following error which I don't have the expertise to address:

Exiting because of FATAL ERROR: could not create FIFO file /mnt/c/Users/gilbe/output/tpm/tmp.fifo.read1
SOLUTION: check the if run directory supports FIFO files.
If run partition does not support FIFO (e.g. Windows partitions FAT, NTFS), re-run on a Linux partition, or point --outTmpDir to a Linux partition.

This error happens with both my compressed and uncompressed fastq files. I also tried change the thread number.

Any chance someone can help me out?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falexdobin%2FSTAR%2Fissues%2F1776&data=05%7C01%7Cy.p.hagemeijer%40umcg.nl%7C298916a9be02450a5d2008db1a9aa12c%7C335122f9d4f44d67a2fccd6dc20dde70%7C0%7C0%7C638133023663110265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0abJkuj1UZlzJiC7Su4PkQYhXpgDGx72EDuweY5nfB0%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACBZ4EJPQRX3AXA3EDL67KDWZ64NVANCNFSM6AAAAAAVMSEVHY&data=05%7C01%7Cy.p.hagemeijer%40umcg.nl%7C298916a9be02450a5d2008db1a9aa12c%7C335122f9d4f44d67a2fccd6dc20dde70%7C0%7C0%7C638133023663110265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aMqSoCMtJvhW1IUFU3PPlBBxUKFRmZccdJ3aUdtwHns%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
De inhoud van dit bericht is vertrouwelijk en alleen bestemd voor de geadresseerde(n). Anderen dan de geadresseerde(n) mogen geen gebruik maken van dit bericht, het niet openbaar maken of op enige wijze verspreiden of vermenigvuldigen. Het UMCG kan niet aansprakelijk gesteld worden voor een incomplete aankomst of vertraging van dit verzonden bericht.

The contents of this message are confidential and only intended for the eyes of the addressee(s). Others than the addressee(s) are not allowed to use this message, to make it public or to distribute or multiply this message in any way. The UMCG cannot be held responsible for incomplete reception or delay of this transferred message.

**Comment by Erikado4** [comment]
Aweome thank you! /tmp/ ended up working! I just wasn't understanding why those files couldn't be written on one of the harddisks. 

Thanks again

**Comment by 1830416002** [comment]
Hello,
I have the same error like you. Can you tell me the new code that work?

**Comment by YPHa** [comment]
Make sure you do not use any paths and/or files in the /mnt/C or any mounted non-linux windows drive (can also apply to external harddrives for example).
If the input data is already on there, you can just copy it into a (virtual) linux partition (for example in your home directory).
If you need the result files in windows you can always copy the result files there afterwards.

Hope this helps.
________________________________

**Comment by ImaanT** [comment]
Dear @YPHa 

I innitially got the error by @Erikado4 
So, I ran the following, adding the /tmp/ to the parameter:
/mnt/c/Users/PC/Desktop/name/GitHub/Lab/STAR/bin/Linux_x86_64$
STAR --runThreadN 4 --genomeDir /mnt/d/name/GenomeDir --readFilesIn /mnt/d/name/subcellFastq_NB --readFilesCommand gunzip -c --outFileNamePrefix /mnt/d/name/STAR_output --outTmpDir /tmp/

I encounter the following error:
EXITING because of fatal ERROR: could not make temporary directory: /tmp//
SOLUTION: (i) please check the path and writing permissions
 (ii) if you specified --outTmpDir, and this directory exists - please remove it before running STAR

May 21 16:55:48 ...... FATAL ERROR, exiting


Did I write down the --outTmpDir parameter correctly? am i supposed to create a folder /tmp/ (I didn't think so, but maybe i missed something in my understanding)

**Comment by ImaanT** [comment]
I was finally able to run STAR by doing the following. It worked for me.

- Created a temporary folder named temp_star in the /tmp directory and set permissions to allow all users to read, write, and execute within this folder.

mkdir -p /tmp/temp_star
chmod 777 /tmp/temp_star

- Assigned the temporary directory to a subdirectory within 'temp_star'

STAR --runThreadN 4 --genomeDir /mnt/d/name/GenomeDir --readFilesIn /mnt/d/name/subcellFastq_NB/S10_L002_cellBarcodesNBs.fastq.gz --readFilesCommand gunzip -c --outFileNamePrefix /mnt/d/name/STAR_output/NB --outTmpDir /tmp/temp_star/temp
