### ISSUE TITLE
Number of splices changed significantly when reference was changed

### ISSUE THREAD

**Issue by XinHuang87** [alexdobin/STAR#188]
Dear Alex,

We've mapped cleaned paired-end RNA-Seq reads to a genome reference with only scaffolds with gene annotation (vs_scaf_w_annot) vs. a genome reference with all scaffolds (vs_all_scaf), and the number of splices changes significantly between two references. Please see attached final output files for three test libraries. 

The genome is large (~2Gb) with a large proportion of the genome being repetitive elements (~68%). In total there are ~155,000 scaffolds, but only ~5,800 scaffolds have gene annotation on them. 

We first generated the first pass genome index for scaffolds with gene annotation by using genomeGenerate (with GFF3, --sjdbOverhang 85, --genomeChrBinNbits 13), mapped individual libraries to this index with default parameters, then generated the second pass genome index by incorporating all three splice junction files from the first mapping (with GFF3, --sjdbOverhang 200, --genomeChrBinNbits 13), and finally mapped individual libraries to this second genome index with default parameters. We repeated this using all genomic scaffolds as the genome reference, using the same parameters above.

The number of splices decreased when using all scaffolds as reference, and the number of GT/AG splice sites decreased, whereas the number of other splice sites increased, comparing using all scaffolds to using scaffolds with gene annotation. Would you have any idea why this pattern occurred? And the number of multi-mapping reads also increased a lot when using all scaffolds as reference. Would it be because there could be duplicated genes on the unannotated scaffolds? It looks like the percentage of uniquely mapped reads dropped when using all scaffolds relative to using scaffolds with gene annotation. If we care about SNP identification using GATK, which only takes into account uniquely mapped reads, should we map the reads to the scaffolds with gene annotation instead of all scaffolds?

Would you have any insight into how this pattern could have occurred? Any feedback would be greatly appreciated! 

[Test03_vs_all_scafLog.final.out.txt](https://github.com/alexdobin/STAR/files/488064/Test03_vs_all_scafLog.final.out.txt)
[Test03_vs_scaf_w_annotLog.final.out.txt](https://github.com/alexdobin/STAR/files/488061/Test03_vs_scaf_w_annotLog.final.out.txt)
[Test04_vs_all_scafLog.final.out.txt](https://github.com/alexdobin/STAR/files/488060/Test04_vs_all_scafLog.final.out.txt)
[Test04_vs_scaf_w_annotLog.final.out.txt](https://github.com/alexdobin/STAR/files/488062/Test04_vs_scaf_w_annotLog.final.out.txt)
[Test07_vs_all_scafLog.final.out.txt](https://github.com/alexdobin/STAR/files/488065/Test07_vs_all_scafLog.final.out.txt)
[Test07_vs_scaf_w_annotLog.final.out.txt](https://github.com/alexdobin/STAR/files/488063/Test07_vs_scaf_w_annotLog.final.out.txt)

**Comment by alexdobin** [comment]
Hi @XinHuang87 

if I understand this problem correctly, when you map against the genome with more scaffolds you see
(i) reduced % of multimappers 70% -> 57% for Test03
(ii) reduced number of splices 2599927 -> 2559919

The (i) is likely due to repetitiveness of the genome - as you add the scaffolds, some of the reads that mapped uniquely to the smaller genome now also map to the added scaffolds and become multimappers. Note, that the number of multimappers increases from 8% to 26%, so the overall mapping rate increases from 78% to 83%

(ii) follows from (i), since the number of splices in the Log.final.out is calculated only for unique mappers. If you want to include multimappers, you would have to work with SJ.out.tab file which counts the splices for both unique and multimappers.

Cheers
Alex

**Comment by XinHuang87** [comment]
Hi Alex,

Thank you very much for your response, it was informative! It makes a lot of sense that the number of splices is calculated for the unique mappers.

Many thanks,

Xin
