### ISSUE TITLE
EM algorithm and likelihood function

### ISSUE THREAD

**Issue by multiomics23** [alexdobin/STAR#1951]
Hi Alex,

I'm working to better understand the EM algorithm. Thank you for incorporating that as one option to manage multimappers.

Does STARsolo approach EM transcript abundance estimation like [TEtranscripts](https://academic.oup.com/bioinformatics/article/31/22/3593/240793?login=false) (e.g., Equations 1-3 in the paper) and/or use the same likelihood function as provided by Kallisto?

Thank you!

**Comment by alexdobin** [comment]
Hi @multiomics23 

The current model is similar to Alevin and Kallisto-bustools. Basically, the probability for a multi-gene UMI to arise from one of the genes is proportional to the expression of the gene. The gene "length" is not taken into account.

**Comment by multiomics23** [comment]
Hi Alex, thank you!

**Comment by jkniehaus** [comment]
Hi Alex,

Thank you for these explanations. I reopened this issue to consolidate information about EM implementation (hope that's all right).
Related to implementing the EM algorithm, could you please clarify whether this is accurate?

STARsolo assigns reads to cell barcodes **prior** to gene mapping. Therefore, the EM implementation for multi-gene multimapped reads will be distributed on a 'per-cell' basis (based on uniquely mapped reads in that cell rather than uniquely mapped reads throughout all cells in the sample). 
Example: If a cell has uniquely mapped reads in Gene X but not Gene Y, then a multimapped read aligning to both X and Y will get assigned to Gene X but not Gene Y (even if other cells have reads that uniquely map to Gene Y). Hope that makes sense.

And a related question:
Is there a way to keep multi-gene multimapped reads only if there are 'supporting' uniquely mapped reads in the corresponding genes, but throw them out when there aren't any uniquely mapped reads to support it? In the example above, if a cell does not have unique reads in either Gene X or Gene Y, then the multi-mapped reads get thrown out.

Thank you for your time,
Jesse
