### ISSUE TITLE
Stranded RNA-seq alignment and chimeric reads

### ISSUE THREAD

**Issue by kevlim83** [alexdobin/STAR#223]
Hi,

I am trying to align stranded RNA-seq data using illumina's standard kit (in tophat we usually specify fr-firststrand meaning that the right most end is the first sequenced, or equivalently the strand of the first mate is reversed while the strand of the second mate is forward), I note from the manual that no further options are required for stranded alignment in STAR. I am also adding these parameters to find chimeric reads:  --chimSegmentMin and --chimOutType WithinBAM

However, I also saw some of your posts mentioning that for chimeric reads, the aligner expects the first mate to be forward while second mate reversed. Can I find out if there is a way to do this in the strand specific direction above?

Please correct me if I am wrong.

Regards,
K

**Comment by DarioS** [comment]
Before you use STAR for chimeric detection, check the insert size distribution of your paired-end dataset. STAR will discard reads that are chimeric and overlapping, which means that the majority of chimeric reads can be simply discarded for some datasets. These kinds of False Negatives are hard to detect in bioinformatics, because the biologists will never experimentally try to validate them.

I read that it's a bug which will be fixed in an upcoming version of STAR.

**Comment by alexdobin** [comment]
Hi @kevlim83 

"the first mate to be forward while second mate reversed" convention only affects the Chimeric.out.junction file. The output of SAM and BAM files does not use this convention, and each mate's strand is recorded according to it's sequence (i.e. the non-chimeric mates are always on opposite strands).

Cheers
Alex
