### ISSUE TITLE
Nextflow + AWS Batch w/ Fusion issue caused by "FATAL ERROR: could not open genome file"

### ISSUE THREAD

**Issue by CharlesARoy** [alexdobin/STAR#2257]
Hi Alex,

I am working on setting up a bioinformatics pipeline that uses RSEM with STAR as the aligner. The pipeline is being developed with Nextflow to be executed by AWS Batch. I'll also be using Nextflow's newish [Fusion](https://docs.seqera.io/fusion) file system which enables one to load data directly from AWS S3 storage for processing (i.e. rather than having to copy it to the EC2 instance first).

Anyway, all that is background that doesn't necessarily matter to the issue at hand.

The RSEM command I am running in AWS is something like:
```
rsem-calculate-expression --paired-end \
    --star \
    --star-gzipped-read-file \
    -p 8 \
    1_CB-15_plv_S23_L002_R1_001.fastq.gz \
    1_CB-15_plv_S23_L002_R2_001.fastq.gz \
    s3://ccbb-nextflow-tests/working_dir/genomes/stargenome/hg38 1_CB-15_plv_S23_L002
```

where the "reference_name" needed by [the rsem-calculate-expression command](https://deweylab.github.io/RSEM/rsem-calculate-expression.html) is "s3://ccbb-nextflow-tests/working_dir/genomes/stargenome/hg38".

The subsequent STAR command generated by RSEM looks like:
```
STAR --genomeDir s3://ccbb-nextflow-tests/working_dir/genomes/stargenome  \
    --outSAMunmapped Within  --outFilterType BySJout  --outSAMattributes NH HI AS NM MD  \
    --outFilterMultimapNmax 20  --outFilterMismatchNmax 999  --outFilterMismatchNoverLmax 0.04  \
    --alignIntronMin 20  --alignIntronMax 1000000  --alignMatesGapMax 1000000  --alignSJoverhangMin 8  \
    --alignSJDBoverhangMin 1  --sjdbScore 1  --runThreadN 8  --genomeLoad NoSharedMemory  \
    --outSAMtype BAM Unsorted  --quantMode TranscriptomeSAM  --outSAMheaderHD @HD VN:1.4 SO:unsorted  \
    --outFileNamePrefix 1_CB-15_plv_S23_L002.temp/1_CB-15_plv_S23_L002  --readFilesCommand zcat  \
    --readFilesIn 1_CB-15_plv_S23_L002_R1.trim.fastq.gz 1_CB-15_plv_S23_L002_R2.trim.fastq.gz
```

This command then errors out with a message like:
```
EXITING because of FATAL ERROR: could not open genome file s3://ccbb-nextflow-tests/working_dir/genomes/stargenome//genomeParameters.txt
```

The RSEM command works when I run it locally, so I think that something about the double slash (`//`) that the STAR code creates when preparing the path to the genomeParameters.txt file causes an issue when referring to AWS S3 objects (as opposed to local files where the // gets reinterpreted as a single slash).

Because the command is prepared by STAR itself, there's nothing obvious that I can do to tweak it before it gets run. Do you have any suggestions?

I am using the latest version of STAR in my [Docker image](https://hub.docker.com/layers/c2roy/rsem_star/latest/images/sha256-17964efb2ed05ee51b46e6cdecb74a2f2dcfb63e2389747904e7413c676467f0), but looking at [other issues](https://github.com/alexdobin/STAR/issues/292), the introduction of the double slash has been a thing since at least 2018.

**Comment by HagemeijerRug** [comment]
Hey,
I am not in any way affiliated with STAR, and have never used the Fusion FS, but I am quite familiar with NextFlow.
And based on the command you pasted, I am guessing that the issue is in your process definition. 

As far as I understand the access to the S3 via Fusion is supposed to be handled by NextFlow, not by the programs you want to call.

If you run something like samtools, bcftools, Python, R, etc. I would expect them not to be able to resolve that URI automatically. I believe that is why Fusion was added to NextFlow in the first place. 

However if you would provide this URI as a path input to a NextFlow process I would assume it to be 'magically'resolved behind the scenes and all I would expect the STAR command to see is something like:
`--genomeDir ./stargenome`

The fact that you have a full URI / path in there suggests that NextFlow (or Fusion?) isn't processing it as a path ...

Could you share the definition of the NextFlow process?

**Comment by CharlesARoy** [comment]
Hi @HagemeijerRug, thanks for taking the time to help me out, that's very kind!

I think that everything was as you suspected. I had initially used `val(stargenome)` instead of `path(stargenome)` in the input of my Nextflow process. When I changed it to path, Nextflow + Fusion was able to auto-adjust the S3 URIs to "local" paths for the given work directory (I think by creating symlinks to the data that gets transferred from S3 to the Fusion cache in /tmp).

A double forward slash was still introduced by STAR, but it wasn't an issue after the S3 URI had been handled by Nextflow.
