### ISSUE TITLE
BUG: next index is smaller than previous, EXITING

### ISSUE THREAD

**Issue by doliv071** [alexdobin/STAR#234]
Hi Alex, 

I'm trying to build the genome index for hg19 downloaded from UCSC and I get the following error:

```BUG: next index is smaller than previous, EXITING```

All the help I've seen on this error are regarding building very small genome indexes. 

Any help would be appreciated.

-Dave

**Comment by alexdobin** [comment]
Hi Dave,

please send me the Log.out file of the failed run.

Cheers
Alex

**Comment by RicardoPluto** [comment]
Hi Dave,

Have you solved this problem?
If so, could you please tell me the solution?
Thank you .

Ricardo
Shen

**Comment by doliv071** [comment]
Sorry for the delay, I ended up pulling a pre-made index from our server and forgot I had opened a ticket. I'll post the log file this evening.

**Comment by doliv071** [comment]
Here is the Log.out file. [Log.out.txt](https://github.com/alexdobin/STAR/files/823006/Log.out.txt)

Thanks for your help.
Dave

**Comment by alexdobin** [comment]
Hi Dave,

still do not know why the genome generation is not working in both cases, your's and Ricardo's.
There is nothing suspicious in the Log.out.txt files. Have you tried the static executable?

Cheers
Alex

**Comment by doliv071** [comment]
I have not, although I did rebuild from source. I'll try the pre-built as soon as I get a chance.

**Comment by yukongoldpotato96** [comment]
Hi Alex,

I am having the same problem building the genome index for hg38, which I downloaded the human genome (ALL) and annotation (ALL) from http://gencodegenes.org/. A user from another post (https://github.com/alexdobin/STAR/issues/244) said that using the genome and annotation files from http://gencodegenes.org worked for him.
Should I use the first GTF file, which contains gene annotations on the reference chromosomes only instead of the second GTF file, which also contains scaffolds, assembly patches and alternate loci (haplotypes)?
Thanks.

Best wishes,
YukKei

**Comment by alexdobin** [comment]
Hi YukKei,

please try the "PRI" files, i.e.
ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M21/gencode.vM21.primary_assembly.annotation.gtf.gz
and
ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M21/GRCm38.primary_assembly.genome.fa.gz

The "ALL" files contain alternative loci and patches, which unnecessarily bloat the genome size, which likely causes this error.

Cheers
Alex

**Comment by yukongoldpotato96** [comment]
Thanks, Alex!

I just gave it another try with the primary assembly for human:
./STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /Users/awlab/Downloads/genome --genomeFastaFiles GRCh38.primary_assembly.genome.fa --sjdbGTFfile gencode.v30.primary_assembly.annotation.gtf --sjdbOverhang -1
Jun 06 07:45:48 ..... started STAR run
Jun 06 07:45:48 ... starting to generate Genome files
Jun 06 07:46:53 ... starting to sort Suffix Array. This may take a long time...
Jun 06 07:47:06 ... sorting Suffix Array chunks and saving them to disk...
Jun 06 09:30:38 ... loading chunks from disk, packing SA...
Jun 06 09:58:03 ... finished generating suffix array
Jun 06 09:58:03 ... generating Suffix Array index
Segmentation fault: 11
It solved the BUG, but I don't understand why the Segmentation fault: 11 killed the run.
Is this because of the --sjdbOverhang -1?
Thanks.

Best wishes,
YukKei

**Comment by alexdobin** [comment]
Hi YukKei,

right, --sjdbOverhang -1 is not allowed, it has to be set ideally to rhe readLength-1, but the default value of 100 will work well in most cases as well.

Cheers
Alex

**Comment by yukongoldpotato96** [comment]
Thanks, Alex! 

I am doing --sjdbOverhang 150 right now!

Best wishes,
YukKei
