### ISSUE TITLE
soft-clipped reads at novel splice junction

### ISSUE THREAD

**Issue by isthisthat** [alexdobin/STAR#240]
Hello,
I'm using STAR 2-pass to detect novel splice junction (from splice-site creating variants). I'm getting the following phenotype where some of the reads do not cross the junction and are soft-clipped instead (the clipped portion perfectly matches the other end of the junction):
![screen shot 2017-02-22 at 16 07 33](https://cloud.githubusercontent.com/assets/1259045/23220249/3e384b84-f919-11e6-8be5-27b62ef36079.png)

Can you suggest some parameters I can tweak to try to get around this? I can point you to an example bam if you need.

Thanks a lot.

**Comment by alexdobin** [comment]
Hi @isthisthat 

is this junction detected in at least one read?
Please send me one of such reads (BAM line), as well as a few reads that were not properly spliced.

Cheers
Alex

**Comment by isthisthat** [comment]
Hi @alexdobin,
Thanks for your reply.
Just to clarify, in the picture above there is a canonical junction where the vertical black bars are, and a novel junction (caused by a splicing-donor-creating variant) some 8bp away
The bam can be downloaded from here: http://wwwdev.ebi.ac.uk/~natalja/star/NA12340.pe.hits.bam
And the position in question is: chr1:180988352 (on hg38)
Half of the reads in that junction span it, while the other half are soft-clipped.
Thank you for your help.

**Comment by isthisthat** [comment]
FYI this is the STAR command used (version 2.5.2b):

    STAR --genomeLoad NoSharedMemory --runThreadN 8 --outSAMunmapped Within
    --outFilterMultimapNmax 10 --outSAMattributes NH HI NM MD AS XS  
    --outSAMstrandField intronMotif   --twopassMode Basic --sjdbOverhang 20  
    --genomeDir Homo_sapiens.GRCh38.dna.toplevel.fa.star --readFilesIn
    NA12340.fq1.gz NA12340.fq2.gz --readFilesCommand zcat
    --outFileNamePrefix NA12340.bam --outSAMtype BAM Unsorted
    --quantMode TranscriptomeSAM

Thanks for your help.

**Comment by alexdobin** [comment]
Hi @isthisthat 

got the BAm files. thanks. From your browser snapshot, can you tell me the ID of one of the reads that are supposed to map to the novel junction, but are soft-clipped instead, as well as one read that actually maps to the junction?

Cheers
Alex

**Comment by isthisthat** [comment]
Hi Alex,
Here is one that is soft-clipped:

    Read name = ERR188277.4719138
    Read length = 63bp
    Mapping = Primary @ MAPQ 255
    Reference span = chr1:180,988,316-180,988,352 (+) = 37bp
    Cigar = 37M26S
    Mate is mapped = yes
    Mate start = chr1:180990036 (-)
    Insert size = 1784
    Second in pair
    Pair orientation = F2R1
    NH = 1
    HI = 1
    NM = 0
    AS = 97

And one that span the novel junction:

    Read name = ERR188277.22145366
    Read length = 63bp
    Mapping = Primary @ MAPQ 255
    Reference span = chr1:180,988,321-180,990,015 (-) = 1,695bp
    Cigar = 31M1632N32M
    Mate is mapped = yes
    Mate start = chr1:180976639 (+)
    Insert size = -13376
    First in pair
    Pair orientation = F2R1
    NH = 1
    HI = 1
    NM = 0
    AS = 115
    XS = -

Thanks again for your help.

**Comment by alexdobin** [comment]
Hi @isthisthat 

I think this is what's going on. The junction in question is non-canonical, but you are requiring strand determination from the motif with  --outSAMstrandField intronMotif --outSAMattributes ... XS .
Since this cannot be done for the non-canonical junctions, STAR soft-clips the first read to avoid this junction. I suspect the 2nd read has a mate that is spliced over canonical or annotated junctions, which allows for strand determination - though the mate for the 2nd junction is not in the BAM file, please check this.

If I map the first read without --outSAMstrandField intronMotif --outSAMattributes ... XS , it splices through the junction:
1       163     chr1    180988316       255     36M1632N27M     =       180990037       1784    CAACTGCTCATCCTGCTGTTCCACGATCAACTGGTGCTGCTGCTGTGCCTGCTGCTCCTCAAT*       NH:i:1  HI:i:1  NM:i:0  MD:Z:63 AS:i:115        jM:B:c,0        jI:B:i,180988352,180989983
1       83      chr1    180990037       255     63M     =       180988316       -1784   CTCGGTCCAGACGCCCATATTTATCTGTTGTTCCAGTGCTCCAGTTCTGGCTGCCACTGTCTC *     NH:i:1   HI:i:1  NM:i:0  MD:Z:63 AS:i:115        jM:B:c,-1       jI:B:i,-1

Cheers
Alex

**Comment by isthisthat** [comment]
Hi Alex,
I confirmed that this improves the issue and gives us better coverage for the non-canonical splice junction. Here's an IGV shot of the initial (top) and new (bottom) alignment with the number of reads at the non-canonical junction in the pop-up window:
<img width="1268" alt="screen shot 2017-03-08 at 10 55 31" src="https://cloud.githubusercontent.com/assets/1259045/23701389/7396d324-03ee-11e7-8120-04af12f1b1c6.png">

There are still some read ends which are soft clipped but most of them are short so potentially captured by other filters. Do you think this is the best we can do?

Thanks again.

**Comment by alexdobin** [comment]
Hi @isthisthat 

please check whether this junction appears in the SJ.out.tab of the 1st pass run.
If it does, then the splices with short overhangs should be captured with the --twopassMode Basic .
If it does not, I will suggest how to tweak the filters to let it through.

Also, you are using --sjdbOverhang 20 which is not optimal for 50-60b reads that you have..
I would just use the default value of 100.

Cheers
Alex

**Comment by isthisthat** [comment]
Hi @alexdobin, we tried your suggestions in the following alignment:
http://www.ebi.ac.uk/~natalja/star/star.NA12340.bam
It seems that the non-canonical splice junction does not appear in the SJ.out.tab. The only junction in the region is the canonical one:

    1	180988346	180989983	2	2	1	21	0	31

Please let us know how to let the non-canonical junction (`chr1:180988352`) through.
Thanks again for all your help.

**Comment by alexdobin** [comment]
Hi @isthisthat 

the BAM file contains a 14 reads mapping to the non-canonical junction - you can check it by using the script from the STAR distribution - it extracts all junctions:
$ samtools view star.NA12340.bam | awk -f extras/scripts/sjFromSAMcollapseUandM.awk > sj
$ grep 180989983 sj
1       180988346       180989983       21      0
1       180988352       180989983       14      0

I think this junction was filtered out from SJ.out.tab because of the proximity filter, which prevents junctions close to other junctions to be reported. You can disable this filter with:
--outSJfilterDistToOtherSJmin    0 0 0 0  . By default, the values are 10  0   5   10, i.e. for non-canonical junctions the min distance between donor/acceptors is 10b.

There is another filter that may be discarding this junction, this is based on the min overhang:
--outSJfilterOverhangMin 30  12  12  12 (by default), which prevents the non-canonical junctions with min overhangs <30.

I suggest that you run with --outSJfilterDistToOtherSJmin 0 0 0 0 0 --outSJfilterOverhangMin 0 0 0 0
and check whether this junction appears in the SJ.out.tab, and the 2nd pass maps more reads to it.
Of course, this will also increase the false junctions in the other loci - the usual sensitivity-precision trade-off. You may want to tweak these parameters to your desired level.

Cheers
Alex

**Comment by isthisthat** [comment]
Hi @alexdobin,
We ended up using the following parameters:

    --outSJfilterOverhangMin 2 2 2 2
    --outSJfilterDistToOtherSJmin 0 0 5 10

Which produced the junctions we were looking for:

    1	180988346	180989983	2	2	1	21	0	31
    1	180988352	180989983	0	0	1	22	0	31

In close to perfect het depth, which is great.  
This is the resulting alignment in IGV (top) compared to previous (bottom):  

![screen shot 2017-03-21 at 13 52 44](https://cloud.githubusercontent.com/assets/1259045/24150495/c6212398-0e3d-11e7-9ec2-e77c53f5986e.png)

And the final complete command-line:

    star --runThreadN 1 --genomeDir hg38.star --genomeLoad NoSharedMemory \
    --readFilesIn NA12340_1.f.fastq NA12340_2.f.fastq --outFileNamePrefix NA12340.pe.hits.bam \
    --outSAMtype BAM   Unsorted --outSAMattributes NH HI NM MD AS --outSAMunmapped Within \
    --outSJfilterOverhangMin 2 2 2 2 --outSJfilterDistToOtherSJmin 0 0 5 10 \
    --outFilterMultimapNmax 10 --sjdbOverhang 100 --twopassMode Basic

Thanks again for all your support. This has been tremendously helpful!

**Comment by isthisthat** [comment]
Hi @alexdobin,
I'm afraid the excitement didn't last very long. Most other instances I looked at had still a few issues. For example:
![screen shot 2017-03-24 at 17 32 57](https://cloud.githubusercontent.com/assets/1259045/24306316/1c51617a-10b8-11e7-9fa0-77190b2e72ad.png)

This is `http://wwwdev.ebi.ac.uk/~natalja/star/HG00143.bam` and the novel splice junction should be at the marked site (`chr4:5745330`) but the reads are soft-clipped still.

**Comment by alexdobin** [comment]
Hi @isthisthat 

is this junction annotated, or are there any reads that support this junction?
In the BAM file, I could only find these junctions:
4       5745326 5748143 1       0
4       5745342 5748147 3       0

Cheers
Alex

**Comment by isthisthat** [comment]
Hi Alex,
This is not an annotated junction but there's a variant causing a splice junction there: chr4:5745330 C->G creating a splicing donor site (GT). The soft-clipped portion of the reads aligns well on the other end of the junction.

**Comment by alexdobin** [comment]
Hi @isthisthat 

OK, this looks like a different problem than the first one.
In this case, all reads have a short overhang over the splice junction, the longest being 7nt.
Such short overhangs are very hard to detect reliably - note that 7-mer will occur randomly every 4^7=16384 bases. 
In your first example, there was at least one read with long overhang that allowed detection of the junction in the 1st pass, and then the reads with short overhangs could be mapped to this junction in the 2nd pass.

I think the best solution in this case is to create a list of potential junctions, and feed it to STAR as if they were annotated. This will allow to detect spliced alignments with short overhangs.
For instance, if you are looking for novel junctions that arise due to variation, you could take each of the new donor (GT) sites and connect it to one (or a few) downstream annotated acceptor sites.

Cheers
Alex

**Comment by isthisthat** [comment]
Great feedback this makes perfect sense. Ok we'll try that. Thanks again!

**Comment by julirsch** [comment]
I had a similar problem and this thread was super helpful. Thanks!
