### ISSUE TITLE
swap being used when memory is free

### ISSUE THREAD

**Issue by CanWood** [alexdobin/STAR#264]
Hi folks,

I'm relatively confident this is a system issue rather that a code issue, but as we only see it with STAR, I thought I'd ask you and the community if you've seen similar symptoms.

On our HPC, if a STAR runs on execution nodes with Opteron 6168,6238, or 6344 processors, the host will start using swap space when only about 75% of physical memory is in use.  It drives the processes in to high I/O wait and grinds to a snails pace.  We do not see this on Opteron  6386 SE, nor any of our Xeon based hosts.

We have set /proc/sys/vm/swappiness to zero on these hosts and it helps, but does not solve the issue.

Again, not blaming the software, just reaching out to see if anyone has experienced the same symptom and has any guidance.

Cheers,
CanWood

**Comment by delocalizer** [comment]
My guess is that this is due to the AMD memory architecture being different — specifically each Opteron physical package contains 2 NUMA nodes, and there are more physical packages per mb on the Opteron boxes. Our 48-core Opteron boxes have 4 x 12-core packages — a total of 8 NUMA nodes — giving 32G/NUMA node on the 256G boxes and just 16G/node on the 128G ones. Contrast with the Xeons which are 2 physical packages per mb, each corresponding to a single NUMA node, so the 256G Xeon boxes have 128G/NUMA node. The Opteron 6386 boxes happen to have 512G of mem so they get 64G/NUMA node — the difference in CPU model is probably a red herring.
