### ISSUE TITLE
STAR running very slowly

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#272]
Hello,

I have a bunch of reads out of which only a few (<1%) map to the genome. For this run particularly STAR seems to execute very slowly. I have provided 20 cores for the job. When I run STAR for libraries where ~90% reads map to the genome then it runs pretty fast. Could you please suggest something that would quicken the process?

Thank you

**Comment by alexdobin** [comment]
Hi Sagnik,

sorry for belayed reply. STAR indeed spends a lot of time trying to map the unmappable reads.
Do these reads map poorly because of high error rate, or because the reference sequence are incomplete.
In the latter case, I strongly recommend mapping to the full genome.

There is also another possible solution that is described here:
[https://groups.google.com/d/msg/rna-star/hJL_DUtliCY/HtpiePlMBtYJ](url)

Cheers
Alex
