### ISSUE TITLE
Using shared memory for the genome indexes

### ISSUE THREAD

**Issue by agamu** [alexdobin/STAR#277]
Hi,

I am trying to align lots of RNAseqs, and in order to improve the computation, I am trying to use the shared memory for the genome indexes in my cluster. It gives the following error, using both LoadAndKeep or LoadAndRemove:

_EXITING because of fatal PARAMETERS error: on the fly junction insertion and 2-pass mappng cannot be used with shared memory genome 
SOLUTION: run STAR with --genomeLoad NoSharedMemory to avoid using shared memory_

Whi is this happening? Is it possible to run STAR with shared memory? Is it because I am using it in a cluster (using SGE)? 

Thanks in advance.

**Comment by alexdobin** [comment]
Hi @agamu,

sorry for belayed reply.
What are your command lines for mapping and genome generation?
If you are inserting the junctions at the mapping stage, you cannot use shared memory indexes, as the junction insertion changes the genome.
Also, I am not sure if memory sharing will improve the performance on your cluster, since most of the time the long genome loading is caused by limited NFS bandwidth.

On my cluster, I use the following trick. If you have more jobs than can be run simultaneously on the cluster, I would recommend splitting your jobs in chunks with a few jobs in each chunk to be run on one node. For each chunk, you can load the genome files to the local storage, and use it for loading genome into RAM. This would reduce the genome loading over NFS.

Cheers
Alex
