### ISSUE TITLE
FATAL ERROR: could not open genome file STARgenomeIndex/genomeParameters.txt

### ISSUE THREAD

**Issue by divnand** [alexdobin/STAR#292]
Hi, 
I am trying to align some RNA Seq data using the STAR aligner. I get the following error as soon as the run starts
FATAL ERROR: could not open genome file STARgenomeIndex/genomeParameters.txt
I initially generated the genome index using the genome generate command and that seemed to proceed without any issues. I have included the log file to this
[LogFile.txt](https://github.com/alexdobin/STAR/files/1142915/LogFile.txt)

My genome Index folder has the following files: 
Genome  SA  SAindex  chrLength.txt  chrName.txt  chrNameLength.txt  chrStart.txt  genomeParameters.txt

and the contents of my genome Parameters file is as follows

[genomeParameters.txt](https://github.com/alexdobin/STAR/files/1142924/genomeParameters.txt)

Am not sure what is going on. I allocate 48gb of memory for the genome generation step. How do I figure out if my files are being generated properly?

Hope you can help me. Thanks.

**Comment by alexdobin** [comment]
Hi @divnand 

this error message likely means that STAR did not find the path to the genomeParameters file.
I would strongly recommend using full (not relative) path in the STAR commands, i.e.
--genomeDir /path/to/STARgenomeIndex/

If this does not help, please send me the Log.out file of the failed run.

Cheers
Alex

**Comment by divnand** [comment]
Thanks Alex. I was working on a cluster and it looks like it needed the complete path. not just the path from my directory. It works now.
Also, it doesnt seem to work if I use zipped input files with the readFilesCommand. I had to unzip the files prior to running STAR.

**Comment by alexdobin** [comment]
Hi @dinvlad 

were the any error messages on screen or at the end of the Log.out file?
If the partition from which you running STAR (i.e. run directory) is FAT, the fifo files will not work and hence the on-the-fly unzipping will not work. You can check that by trying to run inside the home directory:
$ mkfifo tmp1.fifo

Cheers
Alex

**Comment by kemin711** [comment]
I am getting this error message because I am missing this file from my --genomeDir.  I am new to star.  Do I have to generate this file myself?  Or do I copy it from somewhere else?  Thanks in advance.

**Comment by alexdobin** [comment]
Hi Kemin,

this file is generate by STAR when you generate the genome indexes - have you done that step? Did it complete successfully?

Cheers
Alex

**Comment by kemin711** [comment]
Thanks.  Figured it out.  Used the wrong directory. The index was put in a different directory.
Kemin Zhou 858 771-3269 

    On Thursday, May 10, 2018, 3:14:47 PM PDT, alexdobin <notifications@github.com> wrote:  
 
 
Hi Kemin,

this file is generate by STAR when you generate the genome indexes - have you done that step? Did it complete successfully?

Cheers
Alex

**Comment by Cjuery** [comment]
Hi everyone, 

I'm getting back on this discussion. I have also problems with " could not open genome file GENOME_data/star//genomeParameters.txt"
The problem is that i use STAR to map CHIP-seq data (using the method of an article already published). 
I think the problem is that the program doesn't find the files relatives to the transcript annotation (like SA or SAindex) that should be generated by the option  : `--sjdbGTFfile ` during the index creation step.

Do you think it could affect the program run? 

Thank you in advance for your help. 
Cheers

Caroline

**Comment by alexdobin** [comment]
Hi Caroline,

please check that you specified the correct path to the genome index in the --genomeDir option, and of it does not help, please send me the Log.out file.

Cheers
Alex

**Comment by Mederer1993** [comment]
Hey!

I am having problems running STAR after generating the mm10 genome. I am using absolute paths for all files and directories and created the index with `--genomeSAsparseD 2` to overcome the limit of my 32 GB RAM MacBook Pro. 

It seems the index was generated successfully (see [Log.out.txt](https://github.com/alexdobin/STAR/files/2453261/Log.out.txt) file) and I changed the permission for all generated files:

Tobiass-MBP:star_index_mm10_overhang_149 tobiasmederer$ ls -l
total 31435840
-rwxrwxrwx  1 tobiasmederer  staff   2825193028  6 Okt 19:38 Genome
-r-xr-xr-x  1 tobiasmederer  staff        32512  6 Okt 19:38 Log.out
-rwxrwxrwx  1 tobiasmederer  staff  11633022220  6 Okt 19:38 SA
-rwxrwxrwx  1 tobiasmederer  staff   1565873619  6 Okt 19:38 SAindex
-rwxrwxrwx  1 tobiasmederer  staff          493  6 Okt 19:16 chrLength.txt
-rwxrwxrwx  1 tobiasmederer  staff          539  6 Okt 19:16 chrName.txt
-rwxrwxrwx  1 tobiasmederer  staff         1032  6 Okt 19:16 chrNameLength.txt
-rwxrwxrwx  1 tobiasmederer  staff          721  6 Okt 19:16 chrStart.txt
-rwxrwxrwx  1 tobiasmederer  staff     28640439  6 Okt 19:35 exonGeTrInfo.tab
-rwxrwxrwx  1 tobiasmederer  staff     11702051  6 Okt 19:35 exonInfo.tab
-rwxrwxrwx  1 tobiasmederer  staff      1036114  6 Okt 19:35 geneInfo.tab
-rwxrwxrwx  1 tobiasmederer  staff         1030  6 Okt 19:38 genomeParameters.txt
-rwxrwxrwx  1 tobiasmederer  staff      8201106  6 Okt 19:35 sjdbInfo.txt
-rwxrwxrwx  1 tobiasmederer  staff      6438917  6 Okt 19:35 sjdbList.fromGTF.out.tab
-rwxrwxrwx  1 tobiasmederer  staff      6437120  6 Okt 19:35 sjdbList.out.tab
-rwxrwxrwx  1 tobiasmederer  staff      8528277  6 Okt 19:35 transcriptInfo.tab

Still I am getting an error when trying to run STAR:

EXITING because of FATAL ERROR: could not open genome file ./GenomeDir//genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions ([log.out.align.txt](https://github.com/alexdobin/STAR/files/2453263/Log.out.txt))


Can anyone help me out?

Thank you!

**Comment by Mederer1993** [comment]
Short update: 

I don't know how exactly, but I managed to get STAR running now. I decreased the number of threads, played a little with the code, included the gtf file in the command line for the STAR run, specified --runMode and changed the path of my output directory to be in the same parent directory as the genome index. One or more of those did the trick apparently!

This is the command line I ended up with:
`/usr/local/Cellar/STAR/bin/MacOSX_x86_64/STAR \`
`--runMode alignReads \`
`–-runThreadN 6 \`
`--genomeDir /Users/tobiasmederer/data/mouseENSEMBLGRCm38/indexmm10overhang149 \`
`--sjdbGTFfile /Users/tobiasmederer/data/mouseENSEMBLGRCm38/annotation/Mus_musculus.GRCm38.94.gtf \`
`--readFilesIn /Users/tobiasmederer/data/mouseENSEMBLGRCm38/MiSeq/clean_67NR-6.fq \`
`--outSAMtype BAM Unsorted \`

Thanks!

**Comment by alexdobin** [comment]
Hi @Mederer1993 

in the failed run, you used -–genomeDir /Users/tobiasmederer/Desktop/data/Mus_musculus_ENSEMBL_GRCm38/star_indices_overhang_299
which, I guess, was not the right path to the genome directory /.../star_index_mm10_overhang_149

Another suggestion - you do not need to use --sjdbGTFfile /Users/tobiasmederer/data/mouseENSEMBLGRCm38/annotation/Mus_musculus.GRCm38.94.gtf if you already used it at the genome generation step.

Cheers
Alex

**Comment by edevog** [comment]
Is it possible to run STAR without the genome index? I would only like to use STAR to map the genome.

**Comment by alexdobin** [comment]
Hi @edevog 

you need to generate the genome index before mapping - this only needs to be done for a given genome.

Cheers
Alex

**Comment by edevog** [comment]
Thanks @alexdobin.

Could you help me with something else as well?

After generating the genome index, the genomeDir directory I created does not have a "genomeParameters.txt" file so the mapping isn't working and I am getting the error in the title of this issue.

**Comment by alexdobin** [comment]
Hi @edevog 

if this file is missing, it means that the genome generation did not complete.
Where there any error messages? You can also look at the end of Log.out file.

Cheers
Alex

**Comment by PratitiA** [comment]
Hello Alex,

I am using STAR for aligning my trimmed fastq paired files in LINUX.

below is the error which I am getting:

/usr/lib/rna-star/bin/STAR-avx2 --genomeDir /mnt/c/Users/pra4003/Documents/Pratiti/LIP_ESCs/ESC_5-8_2il_p3_and_p15/esc-2il-p15/ --runThreadN 6 --readFilesIn trimmed_R1_combined_fastq trimmed_R2_combined_fastq --outFileNamePrefix /mnt/c/Users/pra4003/Documents/Pratiti/LIP_ESCs/ESC_5-8_2il_p3_and_p15/esc-2il-p15 --outSAMtype BAM SortedByCoordinate --outSAMunmapped Within --outSAMattributes Standard
        STAR version: 2.7.10a   compiled: 2022-01-16T16:35:44+00:00 <place not set in Debian package>
Mar 06 13:10:42 ..... started STAR run
Mar 06 13:10:42 ..... loading genome

EXITING because of FATAL ERROR: could not open genome file /mnt/c/Users/pra4003/Documents/Pratiti/LIP_ESCs/ESC_5-8_2il_p3_and_p15/esc-2il-p15//genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

Mar 06 13:10:42 ...... FATAL ERROR


could you please assist me to resolve this issue.

Thanks,
Pratiti

**Comment by empotts** [comment]
Were you able to fix this?

**Comment by bioruffo** [comment]
The lack of `genomeParameters.txt` may be due to insufficient RAM available for genome indexing. However in this case, STAR will not reach the final "finished successfully" output line.
