### ISSUE TITLE
Using STAR on a cluster

### ISSUE THREAD

**Issue by SKMunster** [alexdobin/STAR#308]
Does anyone have any suggestions for using STAR on a cluster where it can take advantage of multiple nodes, each with multiple processors?  I am thinking that the --runThreadN flag will work on a cluster, especially if I need to assign it to work on specific nodes.  Especially, has anyone tried running STAR on a cluster using a parallelization program like openMPI?

**Comment by alexdobin** [comment]
Hi @SKMunster 

STAR only uses shared memory parallelization (i.e. intra-node) with --runThreadN, but does not use inter-node paralllelization such as MPI. 
If you have a large number of separate RNA-seq datasets to run, you would run them separately on multiple cluster nodes. If you have one large dataset that takes too long to run on one node, you can split the FASTQ files into smaller ones, and run them on separate nodes.

Cheers
Alex

**Comment by ReemaSingh** [comment]
Hi,

I would like to follow up on this thread. Has the inter-node parallelization such as MPI been implemented in the latest release of STAR? if not then is there any plan for implementing this in future? 
Also, instead of splitting the FASTQ files into smaller ones - is there a way to tell STAR to use all the RAM and CPU distributed across different nodes on a cluster?
I would highly appreciate the response.

Thank you,
Reema,
