### ISSUE TITLE
TranscriptomeSAM Problem

### ISSUE THREAD

**Issue by mariagutin** [alexdobin/STAR#315]
I am having an issue with the output from using --quantMode TranscriptomeSAM missing mapped reads relative to the same reads mapped to the corresponding genome.

I simulated 2,166,373 single end reads from a set of transcripts. These transcripts were created using a genome FASTA and its corresponding GTF. Therefore, I would expect nearly all the reads to map regardless of the output being in genome or transcriptome coordinates. However, when using genome coordinates, the flagstat look like this: 

2177316 + 0 in total (QC-passed reads + QC-failed reads)
30026 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
2177316 + 0 mapped (100.00% : N/A)

With the TranscriptomeSAM output:
1403444 + 0 in total (QC-passed reads + QC-failed reads)
1403444 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
1403444 + 0 mapped (100.00% : N/A)

The command used is shown below:

STAR --runThreadN 4 --genomeDir ./${PREFIX}_genome_index --sjdbGTFfile $GTF --outSAMtype BAM Unsorted --outStd BAM_Unsorted --outFileNamePrefix ${PREFIX}_ --readFilesIn $READS --twopassMode Basic --quantMode TranscriptomeSAM --outSAMmapqUnique 60 --outSAMattrRGline ID:$PREFIX LB:$PREFIX PL:ILLUMINA SM:$PREFIX | $SAMTOOLS sort -@ 4 -T ${PREFIX}_sorttemp -o ${PREFIX}_sorted

Normally this would lead me to believe that the reads are mapping to regions outside the transcripts, however, the reads were generated directly from them so that seems unlikely to me.  Any help diagnosing this issue would be greatly appreciated!

**Comment by alexdobin** [comment]
Hi Maria,

I have done tests similar to yours (i.e. generating reads from transcripts with no errors) and found that only a very small (<0.1%) number of reads unmapped or mapped to a "wrong" location.
However, in your case a very large number of reads is unmapped.

Could you test your reads by mapping them with Bowtiw to the transcriptome (you can get the transcript fasta sequences by running RSEM prepare reference, for instance).

If this does not help, please send me a few reads that fail to map back to the transcriptome, as well as the GTF and FASTA file. You can make a small example by restricting these to the smallest chromosome.

Cheers
Alex

**Comment by mariagutin** [comment]
Hi Alex,

Thank you for your prompt reply! 

I didn't use Bowtie, but I did the test you suggested using BWA-mem instead which resulted in all of the reads mapping as expected. 

I've attached files containing the reads, GTF, and a link to the genome FASTA. 

Best,
Maria

[unmapped_transcriptomeSAM_reads.fq.gz](https://github.com/alexdobin/STAR/files/1253956/unmapped_transcriptomeSAM_reads.fq.gz)
[silkbase_mori.gtf.gz](https://github.com/alexdobin/STAR/files/1253961/silkbase_mori.gtf.gz)
You can download the genome FASTA here: http://tigress-web.princeton.edu/~mgutin/

**Comment by alexdobin** [comment]
Hi Maria,

First, I confirmed that these "unmapped" reads are not converted into transcriptome alignments by STAR.
Next, I tried to map these reads to the transcript sequences. I generated transcript sequences using 
$ rsem-prepare-reference --gtf silkbase_mori.gtf bmori_reference.fa RSEMref
The RSEMref.transcripts.fa contains the transcript sequences.
Then I tried to grep the unmapped reads sequence from RSEMref.transcripts.fa and did not find any matches. I also tried to map to the RSEMref.transcripts.fa with STAR and found very few matches.
So it seems to me that the problem is with generating the transcript sequences - how did you do it?

Cheers
Alex

**Comment by mariagutin** [comment]
Hi Alex,

I also tried using $ rsem-prepare-reference --gtf silkbase_mori.gtf bmori_reference.fa RSEMref and found that the output only contained 8705 transcripts. When I generated transcript sequences with the same GTF and reference FASTA using both gffreads and gtf_to_FASTA, I get the full 15726 transcripts. 

For example, transcript BMgn002072 which is missing in the RSEMref output, is the transcript that read1 in the unmapped reads originates from. This might explain why you're seeing very few matches. 

Best,
Maria

**Comment by alexdobin** [comment]
Hi Maria,

thanks for the tests!
You are right, the problem is with the formatting of the GTF file. It looks like some genes only have “CDS” lines and not “exon” lines. I think you can get away with simply replacing the “CDS”  with “exon”. The danger here is that some CDS lines could overlap other exon lines for the same transcript.
However, it does not seem to be the case. I have run 
$ awk '{OFS="\t";if ($3=="CDS") $3="exon"; print}' silkbase_mori.gtf > silkbase_mori.gtf.allExons
and then the STAR genome generation with silkbase_mori.gtf.allExons.
STAR did not complain about overlapping exons and found 15726 transcripts.

After this, 92 of the 100 reads you sent me map to the transcriptome with default parameters. With --quantTranscriptomeBan Singleend --alignSJDBoverhangMin 1, 98 reads map to transcriptome - out of 99 mappable to the genome.

Cheers
Alex

**Comment by mariagutin** [comment]
Hi Alex,

That did the trick, it's all working now. Thank you for all of your help!

Best,
Maria
