### ISSUE TITLE
Use-cases of the NM tag

### ISSUE THREAD

**Issue by yfarjoun** [alexdobin/STAR#319]
There's a discussion in samtools repo https://github.com/samtools/samtools/issues/717 regarding the uses and future definition of the NM tag. 

I noticed that in the past users of Star seemed to care about the NM tag and so I wanted to ask input from users or developers here:

1. What are the known use-cases for the NM (I can think of two Data-QC and Variant calling..but there might be others I'm not thinking about)
2.  What is your take on the definition of NM? in particular regarding ambiguous bases in either the reference or the reads.

Thanks!

**Comment by alexdobin** [comment]
Hi Yossi,

since no one volunteered their opinion, I will chime in.
You may also want to post the question at the STAR mailing group [https://groups.google.com/forum/#!forum/rna-star](url).

Indeeed, variant-calling and QC are the two major applications for the NM tag.
For the former one, we would just want the definition to be consistent between the mapper and variant-caller so that we do not have to re-calculate NM.

For QC, I would prefer that any ambiguous bases, in reference or read or both, will add to the edit distance. This is what STAR does presently, and I think this agrees with Picard's definition. However, if the definition is change I will re-implement it, or maybe even have an option to use different definitions.

Cheers
Alex

**Comment by yfarjoun** [comment]
Thanks Alex. I was wondering what the silence meant...

regarding your comment "consistent between the mapper and variant-caller" is going to be hard to guarantee unless we nail down the definition...which is what the spec is for! 

I guess one question is what combinations of ambiguous bases in the read and the reference be considered a "variant" ? once we know what that is, we can define NM in a consistent way!
