### ISSUE TITLE
Mapping with STAR is taking extremely long

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#329]
Hello,

I have a 5 huge libraries. Each of those libraries have in excess of 300 million reads. Those reads are primarily from 2 organisms - barley and blumeria. I was successful in aligning the reads to the barley genome. About ~92% of the reads align to Barley. I have also used HiSAT2 to align the reads and HiSAT2 could align ~1% of the reads to Blumeria. STAR takes an immensely long time to map the reads to Blumeria. Blumeria has a much smaller genome compared to Barley (only 128 Mb). Here are the settings I used for the run.

cmd="/home/bigdata/sagnik/softwares/STAR/bin/Linux_x86_64/STAR "
    cmd+=" --runThreadN "+str(CPU)
    cmd+=" --genomeDir "+DATA_DIRECTORY_BLUMERIA_GENOME+"/star_index"
    cmd+=" --readFilesIn "+filename
    cmd+=" --outFileNamePrefix "+DATA_DIRECTORY_transcritome_profiling+"/"+mutant+"/"+mutant+"_STAR_blumeria "
    cmd+=" --outSAMstrandField intronMotif "
    cmd+=" --outSAMtype BAM SortedByCoordinate "
    cmd+=" --limitBAMsortRAM 500000000000"
    cmd+=" --outFilterMultimapNmax 100 "

It took me more than a day to align reads to Blumeria for a single library and it still did not finish yet. The STAR run with Barley finished in under 30 mins for a library. 

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik

since 99% of the reads do not map to Blumeria, STAR takes a lot of time trying to squeeze the reads into the wrong genome. The best solution is to make a combined genome of Barley and Blumeria, which will alloy mapping simultaneously to the two genomes, with the best alignments winning.

Another option (if you insist on mapping to Blumeria alone) is to reduce --seedPerWindowNmax to 20 or even smaller values. More discussion on it here: [https://groups.google.com/d/msg/rna-star/hJL_DUtliCY/HtpiePlMBtYJ](url) .

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Thank you for you reply. I will actually use the aligned files to perform read counts per gene /isoform using RSEM. Do you think combining the genomes together will be ok with RSEM?

Thanks

**Comment by alexdobin** [comment]
Hi Sagnik,

I think it will work OK, just make sure that the isoforms and gene have distinct names in the two species.
You would need to generate the RSEM reference for the combined genome and annotations.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Thank you for youre reply. I played around with -SeedPerWindowNMax and I have been able to run it for the smaller organism within an acceptable timeframe.
