### ISSUE TITLE
an error on running the STAR 

### ISSUE THREAD

**Issue by karosse** [alexdobin/STAR#332]
Hello,
I already done 1. cd source 2. make STARforMacStatic CXX=/path/to/gcc 3.make STARforMacStatic
I tried to generate genome indexes files

1.cd source 2.$./STAR --runThreadN 3--runMode genomeGenerate--genomeDir /Users/zty/Desktop/Dir--genomeFastaFiles /Users/zty/Desktop/gene/gencode.vM15.transcripts.fa--sjdbGTFfile /Users/zty/Desktop/gene/gencode.vM15.annotation.gtf--sjdbOverhang 284
but I got :
EXITING because of fatal input ERROR: could not open readFilesIn=Read1
Oct 13 22:11:24 ...... FATAL ERROR, exiting

**Comment by alexdobin** [comment]
Hi @karosse 

I think you are missing a space between 3 and -- in --runThreadN 3--runMode genomeGenerate.
If you scroll to 
##### Initial USER parameters from Command Line:
in the Log.out file, you can see how STAR interpreted your command line.

Cheers
Alex

**Comment by cnoutsos** [comment]
Hi I am trying to use STAR to create an index for a rat genome so I try from a location in my computer right above the folder where the fasta and gtf is located
STAR --runThreadN 6 \ --runMode= genomeGenerate \ --genomeDir /indexRat \ --genomeFastFiles /ratFASTA/Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa \ --sjdbGTFFile /ratFASTA/Rattus_norvegicus.Rnor_6.0.102.gtf \ --sjdbOverhang 99

and I getting an error in the Log.out file

EXITING because of fatal input ERROR: could not open readFilesIn=Read1

Dec 05 17:04:28 ...... FATAL ERROR, exiting

Any help would be highly appreciated.

thank you

**Comment by alexdobin** [comment]
Hi @cnoutsos  

you have an = sign in the ```--runMode=```, please remove = and it should work.

Cheers
Alex

**Comment by OumaeKaede** [comment]
> Hi @cnoutsos
> 
> you have an = sign in the `--runMode=`, please remove = and it should work.
> 
> Cheers Alex

Hey, Alex,
I also met this problem and I've solved it.-The reason is really wierd-OLNY A " "(Space) after my "STAR /", so it does solved LOL
