### ISSUE TITLE
Aligning paired-end reads of different lengths

### ISSUE THREAD

**Issue by justincg327** [alexdobin/STAR#346]
Dear Alex,
Hello, I'm new to STAR and single-cell RNA seq in general. I have paired-sequencing data with 76 base pair reads. However, all the read 1 sequences contain an 8 bp cell barcode, an 8 bp umi, and a poly T region while the read 2 sequences are simply coding sequence. After removing the indexing information at the front of read 1 sequences, the read 1 and read 2 sequences are now of different lengths. Will this affect how STAR aligns the sequences to the genome? When I first tried to align the sequences to the genome I got a very high percent unmapped reads too short and was wondering if it has anything to do with this or if I just need to relax the requirements on read length.

Thanks so much for taking the time to read this and for creating star.

I used UMI_tools to remove cell barcodes and unique molecular identifiers and my log.out file is posted below.
![image](https://user-images.githubusercontent.com/32912443/32861735-a30f0512-ca23-11e7-9d77-648d50f68cbd.png)

**Comment by alexdobin** [comment]
Hi @justincg327,

if the polyT tail is too long, the read may not be mapped because the mapped length will be shorter than the threshold=66% of the total read length (sum of two mates). It might be a good idea to trim the polyT tails before mapping. Or you can reduce the --outFilterMatchNminOverLread and --outFilterScoreMinOverLread from their default values of 0.66 .

Cheers
Alex

**Comment by cramirezs** [comment]
Hello Alex,

Thanks for the kind response. I have another question. My situation is similar, the sequencing was pair-end but with different read length: R1 is 20nt and R2 is 100nt. In the STAR index creation, what value should I give to "--sjdbOverhang", 99? And, since one of my reads is 20nt long, do I need to change the "--seedSearchStartLmax"? Sorry if these questions are silly, I am also new in bioinformatics.

Thank you very much,
Ciro

**Comment by alexdobin** [comment]
Hi Ciro,

these are good questions. 
--sjdbOverhang 99 is the best in this case.
As to --seedSearchStartLmax, you can try to make it smaller than 20 to get more than one seed out of the 20nt read, but I doubt it will help much with mapping this short read - so I would recommend just keeping the default value (50).

Cheers
Alex
