### ISSUE TITLE
Are the indices version specific?

### ISSUE THREAD

**Issue by tjakobi** [alexdobin/STAR#36]
We are running several different version of STAR and used to keep a central folder with STAR indices for  commonly used species. However, we now experience problems during loading the indices:

Shared memory error: 4, errno: Invalid argument(22) EXITING because
of FATAL ERROR: problems with shared memory: error from shmget() or
shm_open(). SOLUTION: check shared memory settings as explained in
 STAR manual, OR run STAR with --genomeLoad NoSharedMemory to avoid
using shared memory

May this issues be related to different STAR versions using the same index? Follow-up question: is the compile option STARlong affecting the indices created?

Thank you very much ,
Tobias

**Comment by alexdobin** [comment]
Hi Tobias,

there were some significant changes in the shared memory usage in the 2.4.1a. The way the genomes are loaded into memory is different from the previous versions, so you cannot load your genome with 2.4.0x, and then use it with 2.4.1x . 

STARlong does not affect the indices.

Cheers
Alex

**Comment by tjakobi** [comment]
Thanks for your answers Alex. Just to be sure: Should we prebuilt 2 slots of indices, one for 2.4.1* and one for < 2.4.1 ?

**Comment by alexdobin** [comment]
Hi Tobias,

yes, if you need to use both old and new versions of STAR with shared memory, you would have to have two indices in separate directories. I believe you can simply copy the index generated with 2.4.1 into a different directory, it should be compatible (I have not tested that thoroughly though) with the earlier versions. The important thing is to use different directories with the two versions of STAR, so that two different shared memory chunks are allocated.

Cheers
Alex
