### ISSUE TITLE
Option for exon Parent feature type?

### ISSUE THREAD

**Issue by Adamtaranto** [alexdobin/STAR#387]
I am attempting to build a genome database with splice junctions from a gff3 file.

For the example below, using these arguments will take the 'exon' feature on line 4 and attempt to assign it to a "Parent" gene with "ID" label "mRNA_1". It is not clear if STAR is looking for the ID "mRNA_1" only in fields with the **feature type "gene"**. If this is the case, it will not find a match. 

Should I then edit the exon "Parents" to point to the parent gene instead? 

It would be useful to have an argument "--sjdbGTFfeatureGene" seeing as exons are variously assigned to parents of type transcript, mRNA, or gene, depending on the annotation source.

Args:
```
--sjdbGTFfeatureExon == exon
--sjdbGTFtagExonParentTranscript == Parent
--sjdbGTFtagExonParentGene == ID
```

```
##gff-version 3
chrm1	prediction	gene	2171	2541	0	-	.	ID=gene_1
chrm1	prediction	mRNA	2171	2541	.	-	.	ID=mRNA_1;Parent=gene_1
chrm1	prediction	exon	2537	2541	.	-	.	ID=exon_1_1;Parent=mRNA_1
```

**Comment by alexdobin** [comment]
Hi Adam,

STAR is only processing --sjdbGTFfeatureExon lines, it does not look for next level parents.
That's why each of the exons lines has to have both "transcript id" and "gene id", as GTF (but not GFF) format requires. So --sjdbGTFtagExonParentGene ID is not going to work.

I would recommend converting GFF to GTF using gffread from cufflinks package:
$ gffread my.gff -T -o my.gtf

Cheers
Alex
