### ISSUE TITLE
Usage of --waspOutputMode

### ISSUE THREAD

**Issue by j3gu** [alexdobin/STAR#403]
Hi,
Recently I saw WASP algorithm has been re-implemented to STAR. I would like to try this option, but I did not find the instruction for how to set up this parameter. Any help would  be appreciated.

Thanks.
Jing

**Comment by alexdobin** [comment]
Hi Arun,

I  hope to release this feature tomorrow in the 2.6.0 release. You can try it now from GitHub master. WASP filtering is activated with --waspOutputMode SAMtag, which will add vW tag to the SAM output:
vW:i:1 means alignment passed WASP filtering, and all other values mean it did not pass.

Cheers
Alex

**Comment by j3gu** [comment]
Hi Alex,

I tried the --waspOutputMode SAMtag using the recent release of STAR, but the output still did show vW tag. I also ran into errors when I added these two arguments together --waspOutputMode SAMtag --outSAMattributes NH HI AS nM NM vA vG vW. Here is the error message "EXITING because of FATAL BUG: unknown/unimplemented SAM atrribute (tag): 12". Do you have any suggestions?

Thanks.
Best,
Jing

**Comment by RyanSchu** [comment]
Hi Alex, 

I appear to be running into the same issue with ver 2.6.0c. I have attempted to run alignment with the `--WaspOutputMode SAMtag --varVCFfile chr1-22.vcf.gz` options and am not getting WASP tags in my alignment file. I have tried it by specifying `--outSAMattributes  vW`, `--outSAMattributes NH HI AS nM NM vA vG vW`, and by leaving it unspecified but am not getting the WASP tags. It does not throw an error as Jing's does. Can you make a recommendation?

Best,
Ryan

**Comment by alexdobin** [comment]
Hi Ryan,

the VCF files have to be unzipped - or you can use process substitution. i.e.:
--varVCFfile <(zcat chr1-22.vcf.gz)

Cheers
Alex

**Comment by RyanSchu** [comment]
Coming back to this issue after a few months, I'm using the most up to date version (2.6.1d) and am getting this response `EXITING because of FATAL INPUT FILE ERROR: could not find any SNPs in VCF file` I've run into this error with a few different vcf files and can't discern why no SNPs are found - any advice as how to proceed?

**Comment by alexdobin** [comment]
Hi Ryan,

sorry for the belayed reply. The VCF file should be formatted like this:
chr1    534324  .       G       T       .       PASS    MTD=bwa_freebayes;KM=1.48;KFP=5;KFF=0   GT      0|1
chr1    550515  .       T       C       .       PASS    MTD=bwa_freebayes;KM=5.00;KFP=0;KFF=0   GT      0|1
chr1    565419  .       C       G       .       PASS    MTD=bwa_freebayes;KM=10.50;KFP=1;KFF=0  GT      1|0

Please post a few SNP lines of your VCF files.

Cheers
Alex

**Comment by RyanSchu** [comment]
Heres a few sample lines:

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  LD1_LD1 ...
1       92675   JHU_1.92674    A       .       .       .       PR      GT      0/0 ...
1       817341  rs3131972       A       C      .       .       PR      GT      0/1 ...
1       826807  1:762187-CT   C        T      .       .       PR      GT      0/0 ...
1       888125  rs13302980     T        .       .       .       PR      GT      0/0 ...
1       899450  rs116452738   G       A      .       .       PR      GT      0/0 ...

Thanks for the response and any help you can give
Ryan

**Comment by alexdobin** [comment]
Hi Ryan,

the ... at the end of each line - is it a separate column, i.e. each line has >10 fields?
This could create a problem as STAR expects only one individual genotype.
If this is the case, please try to cut 10 columns, e.g. with cut -f1-10
If this does not help, please send me a few VCF lines in a file for testing. (Pasting does not work as it seems to replaces tabs with spaces.)

Cheers
Alex

**Comment by RyanSchu** [comment]
Hi Alex,
I did have more than 10 fields in my VCf file. I have filtered it down to my given sample, however I am still receiving this error. I am disallowed from sharing this data publicly, can i contact you at the email listed in the STAR paper?
Best,
Ryan

**Comment by alexdobin** [comment]
Hi Ryan,

sure, please use dobin @ cshl . edu

Cheers
Alex

**Comment by RyanSchu** [comment]
?Hi Alex,


I changed the chromosomal notation as suggested in your last email and it output successfully. Thank you very much for your help on this matter. One additional question, the manual states that "vW:i:1 means alignment passed WASP ltering, and all other values mean it did not pass." I have numerous lines that have not been tagged with any flag. How can this be interpreted?

?

Best,

Ryan Schubert


________________________________

**Comment by alexdobin** [comment]
Hi Ryan,

the vW tag is only present in reads that overlap variants. You can output vA and vG tags to see which alleles the reads overlap, e.g.:
--outSAMattributes NH HI AS nM NM MD vA vG vW

Cheers
Alex

**Comment by tangchao7498** [comment]
Hi Alex,
I used STAR (version2.6.0c and 2.7.1a) for `--varVCFfile S000X1_2.vcf --waspOutputMode SAMtag`,  and I got the error :
EXITING because of FATAL BUG: unknown/unimplemented SAM atrribute (tag): 13

What can be confirmed is that all my genome.fa, GTF file and VCF file contain "chr",  e.g.:
genome.fa:
>chr1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

GTF:
#description: evidence-based annotation of the human genome, version 30 (Ensembl 96), mapped to GRCh37 with gencode-backmap
#provider: GENCODE
#contact: gencode-help@ebi.ac.uk
#format: gtf
#date: 2019-04-02
chr1	HAVANA	gene	11869	14409	.	+	.	gene_id "ENSG00000223972.5_2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; level 2; havana_gene "OTTHUMG00000000961.2_2"; remap_status "full_contig"; remap_num_mappings 1; remap_target_status "overlap";
chr1	HAVANA	transcript	11869	14409	.	+	.	gene_id "ENSG00000223972.5_2"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11

VCF:
chr1	13273	rs531730856	G	C	642	PASS	.	GT	0|0
chr1	47159	rs540662756	T	C	.	PASS	.	GT	0|0
chr1	52238	rs2691277	T	G	999	PASS	.	GT	1|1
chr1	54490	rs141149254	G	A	999	PASS	.	GT	0|1

I don't know where the problem is, can you help me? Thanks.
Best,
Chao Tang

**Comment by tangchao7498** [comment]
Hi,
I got it! The parameter --waspOutputMode are incompatible with SeparateSAMold of --chimOutType. Thanks.
Best,
Chao Tang

**Comment by alexdobin** [comment]
Hi Chao Tang,

you are right, WASP output only works with output (including chimeric) to BAM.

Cheers
Alex

**Comment by dagarfield** [comment]
Hello! Two questions before I launch into my first use of the WASP option. 1) Is it OK if the variants are un-phased? I'm about to try this on a rather polymorphism heavy case (two related species) and I fear exploding the parameter space given the frequency at which multiple variants are overlapped by any given read. 2) Thoughts on end-to-end vs. local?

**Comment by alexdobin** [comment]
Hi @dagarfield 

1. Yes, no phasing is fine - presently phasing is not taken into account at all. All  combinations of variants (indeed exponentially large) are considered, though this is limited to 10 variant per read.
2. I generally prefer local alignment, as it reduces the errors at the read ends.

Cheers
Alex

**Comment by dagarfield** [comment]
Oh, great!
And what should happen in the case that 10 variants is reached?

**Comment by alexdobin** [comment]
It will add vW:i:7 SAM tag to such reads.
10 is a hard-coded parameter, if you feel you need a few more variants per read, I could make it a user-definable parameter - though it will quickly become very slow.
The best solution would be to incorporate phasing, of course...

**Comment by dagarfield** [comment]
In this case, I could add phasing, so additional variants as an option
would not be unwelcome. :)

**Comment by alexdobin** [comment]
Phasing would require some significant changes in the code, so it's not going to happen soon.
Also, I would point out that if you have 10 variants per 100b reads, it's equivalent to 10% error rate, which will be problematic to align confidently. In this case, I would recommend building the diploid genome from phased variants.

**Comment by dagarfield** [comment]
Hi Alex,

I shall do just that (with the diploid genome). In any event, I'm getting a
segmentation fault and core dump just after the step "Finished Sorting VCF
Data" and "Started Mapping". Any guesses? Simply too little memory for so
many variants?

**Comment by alexdobin** [comment]
Hi @dagarfield 

please send me the Log.out file.

Cheers
Alex

**Comment by dagarfield** [comment]
This should be they. Thanks!
[relevant_log_files.tar.gz](https://github.com/alexdobin/STAR/files/3462168/relevant_log_files.tar.gz)

**Comment by alexdobin** [comment]
Hi @dagarfield 

nothing suspicious in the Log.out file. I think it's the problem you alluded to in the OP: the explosion of the search space for multiple variants overlapping one read. You have ~8M SNVs for ~180Mbase genome, i.e. SNV every 20b. I think creating a diploid genome might be the only viable option.

Cheers
Alex

**Comment by dagarfield** [comment]
OK, good to know. I'll reserve the WASP option for less divergent
individuals. :)
Would you consider this still a guide to good practice for diploid genomes
in WASP? https://groups.google.com/forum/#!topic/rna-star/zs7qsaDidcA

While we do have indels between our two lines, they aren't super common,
and I'd planned a much more simple "make two genomes, merge, map, take
unique reads to be allele-specific" kind of approach. I guess the chain
file just formalises this?

**Comment by alexdobin** [comment]
Hi @dagarfield 

yes, this strategy works well for personal diploid genomes in humans. We use AlleleSeq to generate the genome sequence and chain files. You are right - if you only include SNV, "make two genomes, merge, map, take unique reads to be allele-specific" will work, i.e. you do not need to convert coordinates, no need for chain files, conversion of GTFs, etc.

Cheers
Alex

**Comment by demis001** [comment]
I am trying to map an RNA-Seq from hybrid mouse to a mouse reference genome. I read the WASP nature method paper, it looks like it will improve the accuracty of the alignment in this context. I have downloaded SNP and indels from "ftp://ftp-mouse.sanger.ac.uk/REL-1807-SNPs_Indels/"used it after unpigz it. `- -varVCFfile /data1/genome/mm38_r100/mgp.v6.merged.norm.snp.indels.sfiltered.vcf --waspOutputMode SAMtag` . The alignment completed without any problem. I inspected the bam file and it has nM tag. eg. nM:i:0, nM:i:1.... nM:i:8.

The problem is there was no difference when I compare the alignment log file in the alignment percentage with and without WASP mode.  I got 68.95% uniquely aligned reads. I think this will affect the quantification with htseq-count.  Any idea?

   Started job on |	Jul 29 15:07:01
                             Started mapping on |	Jul 29 15:19:29
                                    Finished on |	Jul 29 16:09:29
       Mapping speed, Million of reads per hour |	34.22

                          Number of input reads |	28514043
                      Average input read length |	282
                                    UNIQUE READS:
                   Uniquely mapped reads number |	19660811
                        Uniquely mapped reads % |	68.95%
                          Average mapped length |	279.86
                       Number of splices: Total |	22121723
            Number of splices: Annotated (sjdb) |	21873869
                       Number of splices: GT/AG |	21930341
                       Number of splices: GC/AG |	148223
                       Number of splices: AT/AC |	9686
               Number of splices: Non-canonical |	33473
                      Mismatch rate per base, % |	0.36%
                         Deletion rate per base |	0.02%
                        Deletion average length |	2.54
                        Insertion rate per base |	0.02%
                       Insertion average length |	2.36
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	1443490
             % of reads mapped to multiple loci |	5.06%
        Number of reads mapped to too many loci |	73499
             % of reads mapped to too many loci |	0.26%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	3819017
                 % of reads unmapped: too short |	13.39%
                Number of reads unmapped: other |	3517226
                     % of reads unmapped: other |	12.34%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

**Comment by alexdobin** [comment]
Hi Dereje,

I will link to this post and reply to it in your other thread https://github.com/alexdobin/STAR/issues/982

Cheers
Alex

**Comment by tingqi** [comment]
Hi Alex,

I have two questions about using "--waspOutputMode". 1) Is it OK to use the VCF files from the same data set but with different individual names? For example, in fastq file, the ID is "FF_001", while in VCF file, the ID is "001". 2) In my VCF file, each chromosome has an VCF file, do I need to merge 22 VCF files into 1 VCF file or there is another way that I do not need merge these 22 VCF files? Thank you in advance. 

Best Wishes,
Ting

**Comment by hadasbi** [comment]
Hi,

I'm trying to use the --waspOutputMode option on a dataset. I'm using a COSMIC vcf file, filtered for SNPs only. I added the prefix "chr" to the first column to make it match the chromosome names in my genome (Before I did that, I got the same error).

This is how I run star:
`STAR --runMode alignReads --genomeDir ../../.. --readFilesCommand zcat --readFilesIn ../fastq_files/R1.fastq.gz ../fastq_files/R2.fastq.gz --outFileNamePrefix init --outSAMtype BAM Unsorted SortedByCoordinate  --outSAMattributes NH HI AS nM NM MD jM jI XS MC ch vA vG vW --varVCFfile CosmicCodingMuts_SNPs.vcf --waspOutputMode SAMtag
`

I get the error: 
`EXITING because of FATAL INPUT FILE ERROR: could not find any SNPs in VCF file: CosmicCodingMuts_SNPs.vcf
SOLUTION: check formatting of the VCF file; unzip VCF file or use process substitution.
`

This is how the vcf looks like:
chr1    65797   COSV58737189    T       C       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN23957695;SNP;CDS=c.9+224T>C;AA=p.?;HGVSC=ENST00000641515.2:c.9+224T>C;HGVSG=1:g.65797T>C;CNT=1
chr1    66041   COSV58737025    A       G       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN24406961;CDS=c.9+468A>G;AA=p.?;HGVSC=ENST00000641515.2:c.9+468A>G;HGVSG=1:g.66041A>G;CNT=1
chr1    66131   COSV58737120    C       G       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN17493387;CDS=c.9+558C>G;AA=p.?;HGVSC=ENST00000641515.2:c.9+558C>G;HGVSG=1:g.66131C>G;CNT=1
chr1    66312   COSV58736797    A       T       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN7277204;CDS=c.9+739A>T;AA=p.?;HGVSC=ENST00000641515.2:c.9+739A>T;HGVSG=1:g.66312A>T;CNT=1
chr1    66371   COSV58737143    A       T       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN17943257;CDS=c.9+798A>T;AA=p.?;HGVSC=ENST00000641515.2:c.9+798A>T;HGVSG=1:g.66371A>T;CNT=1
chr1    66373   COSV58736978    A       T       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN4902613;CDS=c.9+800A>T;AA=p.?;HGVSC=ENST00000641515.2:c.9+800A>T;HGVSG=1:g.66373A>T;CNT=2
chr1    66605   COSV58736995    T       A       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN28548666;CDS=c.9+1032T>A;AA=p.?;HGVSC=ENST00000641515.2:c.9+1032T>A;HGVSG=1:g.66605T>A;CNT=1
chr1    66795   COSV58737166    T       A       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN28504759;CDS=c.9+1222T>A;AA=p.?;HGVSC=ENST00000641515.2:c.9+1222T>A;HGVSG=1:g.66795T>A;CNT=1
chr1    66814   COSV58737064    A       G       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN22517283;SNP;CDS=c.9+1241A>G;AA=p.?;HGVSC=ENST00000641515.2:c.9+1241A>G;HGVSG=1:g.66814A>G;CNT=2
chr1    66864   COSV58736928    C       T       .       .       GENE=OR4F5_ENST00000641515;STRAND=+;LEGACY_ID=COSN21650154;CDS=c.9+1291C>T;AA=p.?;HGVSC=ENST00000641515.2:c.9+1291C>T;HGVSG=1:g.66864C>T;CNT=1


Any idea what's wrong?
Thanks,
Hadas
