### ISSUE TITLE
Causing space error while aligning RNA-seq reads using STAR

### ISSUE THREAD

**Issue by ammarsabircheema** [alexdobin/STAR#430]
Hi Alex,
           I am trying to align RNA-seq reads using STAR through following commands:
           `STAR --runMode alignReads --runThreadN 26  --outSAMtype BAM  SortedByCoordinate Unsorted --sjdbOverhang 100  --genomeDir wheat --readFilesIn G3_cleaned_R1.fastq G3_cleaned_R2.fastq --sjdbGTFtagExonParentTranscript wheat.gff3
                                   Jun 05 13:53:59 ..... started STAR run
                                  Jun 05 13:53:59 ..... loading genome
                                 Jun 05 14:07:12 ..... started mapping
                                 Jun 05 18:42:47 ..... started sorting BAM
                             EXITING because of FATAL ERROR: number of bytes expected from the BAM bin   does not agree with the actual size on disk: 509186583   0   45                                                                                        
                  EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 648593301   0   47                                                                                        
       Jun 05 18:42:47 ...... FATAL ERROR, exiting                                                                                                                                                                                      
      Jun 05 18:42:47 ...... FATAL ERROR, exiting                                                                                                                                                                                      
      EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 660412146   0   46                                                                                        
    Jun 05 18:42:47 ...... FATAL ERROR, exiting                                                                                                                                                                                      
     EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 470931698   0   44                                                                                        
     Jun 05 18:42:47 ...... FATAL ERROR, exiting                                                                                                                                                                                      
     EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 653155717   0   43                                                                                        
   Jun 05 18:42:47 ...... FATAL ERROR, exiting                                                                                                                                                                                      
   Segmentation fault (core dumped)`  
Although there is much free space on my system as shown below:
`> df -Th
  Filesystem     Type      Size  Used Avail Use% Mounted on
  devtmpfs       devtmpfs   63G     0   63G   0% /dev
  tmpfs          tmpfs      63G  136K   63G   1% /dev/shm
  tmpfs          tmpfs      63G  1.9M   63G   1% /run
  tmpfs          tmpfs      63G     0   63G   0% /sys/fs/cgroup
  /dev/sda3      ext4      3.6T  1.4T  2.2T  39% /
  /dev/sda2      ext4      9.8G   57M  9.2G   1% /boot
  tmpfs          tmpfs      13G     0   13G   0% /run/user/480
  tmpfs          tmpfs      13G   16K   13G   1% /run/user/1000`

As far as the version of STAR is concerned its latest:
`STAR --version
STAR_2.6.0b
`
How this error can be removed?

**Comment by alexdobin** [comment]
Hi @ammarsabircheema 

are you trying to run multiple STAR jobs from the same work directory? This is not allowed, but would explain why you are getting multiple FATAL error messages.
Each sample has to be run in a different directory.

Cheers
Alex

**Comment by ammarsabircheema** [comment]
Hi Alex, 
       First I indexed the genome in this directory and now I am mapping reads in the same directory,  I am not running multiple jobs at the same time,  but as I said  first I indexed genome then mapped reads,  is this not allowed?

**Comment by alexdobin** [comment]
Hi @ammarsabircheema 

this is allowed but not recommended - though you are specifying --genomeDir wheat , so you mapping directory is actually one level up of the genome directory. Please try to use 2.6.0c version of STAR as a/b were unstable. If it does not help, please send me Log.out file.

Cheers
Alex

**Comment by ammarsabircheema** [comment]
OK I will move to 2.6.0c and see if it works otherwise will come back with log.out file.

**Comment by jjoets** [comment]
Dear Alex,
I get the same error using the 2.6.1c version for mapping a set of pairs of fastq files at a time (several samples).
I uploaded the log file.

Thanks for your help

Johann

[F2Log.out.txt](https://github.com/alexdobin/STAR/files/2620873/F2Log.out.txt)

**Comment by pandadad** [comment]
Hi Alexdobin,
I am also getting the same trouble for these two days. I looked at some suggestion that you mentioned before and the issue is still there. I always deleted the _STARtmp file before re-running the script. So frustrated. Is there any further suggestion from you? 
Many thanks
Yong
![ERROR](https://user-images.githubusercontent.com/51213985/58741017-9dc35480-83c9-11e9-8b86-9e55bec7b772.JPG)

**Comment by pandadad** [comment]
reduced the number of cores for using. Then it works.

**Comment by alexdobin** [comment]
Hi @pandadad 

what STAR version are you using?
2.6.1d should have thrown an error at the very beginning of the run, suggesting to increase 
$ ulimit -n 10000
Reducing the number of cores is fine tou, usuall mapping speed saturates at  >~20 threads.

Cheers
Alex

**Comment by margo865** [comment]
Hi alexdobin,

I'm using version 2.7.2b and I get the same error message:

Oct 10 16:12:26 ..... started STAR run
Oct 10 16:12:28 ..... loading genome
Oct 10 16:13:14 ..... started mapping
Oct 10 16:23:16 ..... finished mapping
Oct 10 16:24:04 ..... started sorting BAM

EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: Expected bin size=722099377 ; size on disk=560831999 ; bin number=47

Oct 10 16:24:06 ...... FATAL ERROR, exiting

I have ran this script before with other sample and it worked.

I tried to use the ulimit -n 10000 but it still didn't work. Also tried to change the number of cores and no results.

Could you help me with this?

I write here my script:

ulimit -n 10000

STAR --genomeDir /proj/snic2019-8-129/genome/star --runThreadN 16 --readFilesIn /proj/snic2019-8-129/raw/CC1FGANXX_3_21_1.fastq.gz /proj/snic2019-8-129/raw/CC1FGANXX_3_21_2.fastq.gz --outFileNamePrefix /proj/snic2019-8-129/mapping/3_21/CC1FGANXX_3_21. --outSAMattributes All --outSAMtype BAM SortedByCoordinate --readFilesCommand zcat

Thanks a lot!!

**Comment by alexdobin** [comment]
Hi @margo865 

this is likely a problem with not enough space on disk, the amount of space you need is at least ~3*sizeOfGzippedFastqs.

Cheers
Alex

**Comment by madhuri2897** [comment]
EVEN WITH SPACE AVAILABLE IT IS CREATING THE SAME ERROE
