### ISSUE TITLE
Reduced mapping reported in some cases 

### ISSUE THREAD

**Issue by ranjit58** [alexdobin/STAR#464]
Hi Alex,

I have a weird situation where for my some sample the mapping rate reported by STAR is low. Rerunning the incorrect (sample providing low mapping) sample again reports correct numbers without any code/parameter changes.  It can be my system specific thing (no clue though) but thought to ask if you have seen anything like this before. STAR logs in both cases are mostly similar except the progress file where it shows decrease in mapping rate  in incorrectly processed samples. 
I am using version STAR_2.5.3a, snakemake workflow, and aligning RNA reads on small genome or ensemble human genome. STAR was installed via conda.

Attaching log files (renamed and 1.txt and 2.txt where run 1 has reported incorrect results and rerunning run 2 produces correct result)

I am sorry if I am missing something obvious and let me know if you have any questions.

[mRNA1_globin_Log.final.out1.txt](https://github.com/alexdobin/STAR/files/2255870/mRNA1_globin_Log.final.out1.txt)
[mRNA1_globin_Log.out1.txt](https://github.com/alexdobin/STAR/files/2255871/mRNA1_globin_Log.out1.txt)
[mRNA1_globin_Log.progress.out1.txt](https://github.com/alexdobin/STAR/files/2255872/mRNA1_globin_Log.progress.out1.txt)
[mRNA1_globin_Log.final.out2.txt](https://github.com/alexdobin/STAR/files/2255873/mRNA1_globin_Log.final.out2.txt)
[mRNA1_globin_Log.out2.txt](https://github.com/alexdobin/STAR/files/2255874/mRNA1_globin_Log.out2.txt)
[mRNA1_globin_Log.progress.out2.txt](https://github.com/alexdobin/STAR/files/2255875/mRNA1_globin_Log.progress.out2.txt)

**Comment by alexdobin** [comment]
Hi Ranjit,

I have never encountered such a problem, and I cannot think of anything to explain it. There is nothing suspicious in the Log.out files. The Log.progress.out files show good mapping rate first, and then it starts to decay, so my suspicion would be on some kind of a problem when reading these files. As you output the unmapped reads, could you look at a few reads that were unmapped in the bad run but mapped in the good run - maybe we will see what the problem is.

Another thing to try would be to re-run the same case several time to see if the problem is reproducible.
Cheers
Alex

**Comment by ranjit58** [comment]
Hi Alex,

Just to add more info on the thread. When I moved the pipeline (made using snakemake  and includes other tools like STAR, picard, rnaseqc,rseqc, samtools etc) to different computer the problem still shows up. So it is not a system dependent issue (like faulty hardware or RAM).

Will investigate more when I find some time.
thanks,
Ranjit
