### ISSUE TITLE
STAR 2.6 yields empty bam files (when used as part of STAR-Fusion / FusionInspector)

### ISSUE THREAD

**Issue by plijnzaad** [alexdobin/STAR#474]
Hi, 

[I just created an issue for this in the STAR-Fusion repo](https://github.com/STAR-Fusion/STAR-Fusion/issues/92). 

The problem is there with STAR 2.6.0c and 2.6.1c, but not with 2.5.3c, and I can reproduce it.

**Comment by plijnzaad** [comment]
Final comment: the problem persists van recompiling the binary (previously I used the precompiled dynamically linked version that is included in the distribution). Details of compiler and system are:
```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core

$ uname -a 
3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alexdobin** [comment]
Hi Philip,

I have not made any serious change to compilation/linking.
could you please create a minimal example that causes this problem, and send it to me?
I will try to reproduce it.

Cheers
Alex

**Comment by plijnzaad** [comment]
Hi Alex,

I have one (28 MB) which I sent to Brian, and Brian sent me a an example
(78 MB) which reproduces the problem. They are too big to send by e-mail, I
can use WeTransfer but which address to use ?

Regards,

Philip

2018-08-17 16:16 GMT+02:00 alexdobin <notifications@github.com>:

**Comment by alexdobin** [comment]
Hi Philip,

could you please send it to adobin at gmail.com?

Thanks a lot!
Alex

**Comment by plijnzaad** [comment]
Hi Alex,

I sent two cases that reproduce the bug (just unpack, and adjust the
'run.sh' script so that $star points to the right location of the STAR
binaries).

Both cases come from running STAR-Fusion, which constructs a virtual genome
of fusion genes, to which the evidence reads are aligned. The file
'teststar.tar.gz' comes from me, the file 'for_phil.tar.gz' comes from
Brian Haas.

The problem for the shared-library versions occurs both with the
precompiled binary that is part of the distribution as well as with a
freshly  compiled on.


Many thanks, Philip

2018-08-21 17:07 GMT+02:00 alexdobin <notifications@github.com>:

**Comment by alexdobin** [comment]
Hi Philip,

thanks for the file, I will try to reproduce the problem.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Philip,

thanks again for the test example.
This issue was caused by --outSAMfilter KeepOnlyAddedReferences parameter.
This option only makes sense if the references are added on-the-fly with --genomeFastaFiles option.
If no references are added, then  --outSAMfilter KeepOnlyAddedReferences would generate no alignment. Now STAR will throw an error after reading parameters.
Also, if the sorted BAM was empty, it was not correctly formatted - I fixed that as well.

Interestingly, the statically compiled (and earlier) versions were ignoring this parameter because of yet another bug with uninitialized memory, which I also fixed.

Please try the new version at GitHub master - however, you can continue using the old one and simply remove the --outSAMfilter KeepOnlyAddedReferences option.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Philip,

I hope to release 2.6.1b patch tomorrow.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Philip,

sorry for the delay, 2.6.1b is out.
[https://github.com/alexdobin/STAR/releases/tag/2.6.1b](https://github.com/alexdobin/STAR/releases/tag/2.6.1b)

Cheers
Alex
