### ISSUE TITLE
fatal input error

### ISSUE THREAD

**Issue by flippy23** [alexdobin/STAR#504]
hello, 

i am having issues running STAR to generate genome indices. this is the command i'm using:

pathto/Linux_x86_64_static/STAR --runThreadN 40 --runMode genomeGenerate --genomeDir /pathto/Genome \ --genomeFastaFiles /Genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa \ --sjdbGTFfile /Genome/Homo_sapiens.GRCh38.94.gtf

the error i'm getting is: 

Oct 15 08:55:53 ..... started STAR run
Oct 15 08:55:53 ... starting to generate Genome files

EXITING because of INPUT ERROR: could not open genomeFastaFile: -

Oct 15 08:55:53 ...... FATAL ERROR, exiting

reading past thru other posts and not seeing my solution there. these are the correct paths. i've downloaded the latest fasta and gtf files via ensembl:

wget ftp://ftp.ensembl.org/pub/release-94/gtf/homo_sapiens/Homo_sapiens.GRCh38.94.gtf.gz
gunzip Homo_sapiens.GRCh38.94.gtf.gz
wget ftp://ftp.ensembl.org/pub/release 94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
gunzip Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

**Comment by flippy23** [comment]
update: 

i downloaded via gencode to see if there were any differences. still encountered the same error.

**Comment by alexdobin** [comment]
Hi @flippy23 

you need to specify the full path to fasta and gtf files, i.e.
instread of 
--genomeFastaFiles /Genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa
you need to have
--genomeFastaFiles /full/path/to/Genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa

Cheers
Alex

**Comment by alexdobin** [comment]
Sure, no worries, thanks for letting me know.
Cheers
Alex

**Comment by ELMMA-FUNNY** [comment]
hello,I specify the full path to fasta and gtf files ,but the problem  
EXITING because of INPUT ERROR: could not open genomeFastaFile
still exists.I don't know why.
Could you help me? Thanks.

**Comment by ELMMA-FUNNY** [comment]
hello@alexdobin 

I specify the full path to fasta and gtf files ,but the problem
EXITING because of INPUT ERROR: could not open genomeFastaFile
still exists.I don't know why.
Could you help me? 

Thanks.
ELMMA-FUNNY

**Comment by alexdobin** [comment]
Hi ELMMA-FUNNY 

It is likely a problem with formatting of the command line.
Please send me the Log.out file.

Cheers
Alex

**Comment by nonglukplo** [comment]
Hi @alexdobin

I have the same problem too. I even put the file on my current directory, but still got the same problem.

Can you please help me?

**Comment by NGuslund** [comment]
Hi,
I am also having similar error message:

STAR \
--runThreadN 10 \
--runMode genomeGenerate \ 
--genomeFastaFiles GCF_902167405.1_gadMor3.0_nu_mt_for_Naomi_clean.fasta \
--sjdbGTFfile GCF_902167405.1_gadMor3.0_genomic.renamed.dropseq.final.gata2.gtf \
--sjdbOverhang 149 \
--genomeDir .
	STAR --runThreadN 10 --runMode genomeGenerate " "
	STAR version: 2.7.10b   compiled: 2023-03-24T16:16:46+01:00 c1-26:/tmp/vegarde/build/STAR/2.7.10b/GCC-11.3.0/STAR-2.7.10b/source
Aug 17 12:58:04 ..... started STAR run
!!!!! WARNING: Could not move Log.out file from ./Log.out into ./GenomeDir/Log.out. Will keep ./Log.out

Aug 17 12:58:04 ... starting to generate Genome files

EXITING because of INPUT ERROR: could not open genomeFastaFile: -

Aug 17 12:58:04 ...... FATAL ERROR, exiting
-bash: --genomeFastaFiles: command not found

Below is the read out of the Log.out file. Any advice would be appreciated!

STAR version=2.7.10b
STAR compilation time,server,dir=2023-03-24T16:16:46+01:00 c1-26:/tmp/vegarde/build/STAR/2.7.10b/GCC-11.3.0/STAR-2.7.10b/source
STAR git: 
##### Command Line:
STAR --runThreadN 10 --runMode genomeGenerate " "
##### Initial USER parameters from Command Line:
###### All USER parameters from Command Line:
runThreadN                    10     ~RE-DEFINED
runMode                       genomeGenerate   " "        ~RE-DEFINED
##### Finished reading parameters from all sources

##### Final user re-defined parameters-----------------:
runMode                           genomeGenerate   " "   
runThreadN                        10

-------------------------------
##### Final effective command line:
STAR   --runMode genomeGenerate   " "      --runThreadN 10
----------------------------------------

Number of fastq files for each mate = 1
ParametersSolo: --soloCellFilterType CellRanger2.2 filtering parameters:  3000 0.99 10
Finished loading and checking parameters
--genomeDir directory created: ./GenomeDir/
!!!!! WARNING: Could not move Log.out file from ./Log.out into ./GenomeDir/Log.out. Will keep ./Log.out

Aug 17 12:58:04 ... starting to generate Genome files

EXITING because of INPUT ERROR: could not open genomeFastaFile: -

Aug 17 12:58:04 ...... FATAL ERROR, exiting
Log.out (END)

**Comment by NGuslund** [comment]
The GCF_902167405.1_gadMor3.0_nu_mt_for_Naomi_clean.fasta fasta file is present in the directory I am running the command...

**Comment by NGuslund** [comment]
I solved the problem! There was a space at the end of GCF_902167405.1_gadMor3.0_nu_mt_for_Naomi_clean.fasta!
