### ISSUE TITLE
*OUTPUT FILE* error with STAR 2.6.1d but not 2.5.1b_modified

### ISSUE THREAD

**Issue by scottkall** [alexdobin/STAR#528]
I recently upgraded to STAR 2.6.1d, but upon the first run I get the following error related to my `--outFileNamePrefix /mnt/scratch/SD-SC-100_S4/SD-SC-100_S4.`. I do have write access to this directory, and most of the file objects exist (everything up to ...`20/15`). And my `ulimit -n` is 524288.

Oddly, when I used my pervious version (STAR_2.5.1b_modified) for both indexing and mapping, it worked. I'd like to use the new version if possible, since with this older version we've experienced a different known issue.

Error:

```
Nov 29 15:07:29 ..... started STAR run
Nov 29 15:07:29 ..... loading genome
Nov 29 15:08:56 ..... started mapping

BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file /mnt/scratch/SD-SC-100_S4/SD-SC-100_S4._STARtmp//BAMsort/20/16
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.
```

My run command is:

```
STAR --runThreadN 31 --genomeDir <redacted> --outFilterIntronMotifs RemoveNoncanonical  \
                    --outFilterMismatchNoverLmax .02 --outSAMmultNmax 1 --outFilterMultimapNmax 1  \
                    --outFilterMatchNminOverLread .5 --outSAMtype BAM SortedByCoordinate  \
                    --outSAMattributes NH HI AS nM NM MD --genomeLoad LoadAndKeep  \
                    --outFileNamePrefix /mnt/scratch/SD-SC-100_S4/SD-SC-100_S4. --limitBAMsortRAM 15000000000 --readFilesIn <redacted file1 file2 file3 etc>
```

Possibly related is #512, especially near the bottom. Thanks much for any help.

**Comment by alexdobin** [comment]
Hi Scott,

if this error is thrown, it means STAR could not create the file for some reason, the previous versions of STAR just did not make that check, so it's strange that you had no problems with sorting with the previous version.
Please try 2.6.1c with exactly the same configuration - it does not contain that check, but contains almost everything else that 2.6.1d does.

Cheers
Alex

**Comment by aubreybailey** [comment]
Can confirm that this is still present in 2.7.0a
Mapping with 24 threads fails with this error message. Mapping with 12 proceeds as normal.

**Comment by alexdobin** [comment]
Hi Aubrey,

if you see a message like this:
`BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file 
`
it - likely - is caused by the value of ulimit -n being too small, =1024 for most  systems by default. 
You could either reduce the number opf threads, or increase the limit with
$ ulimit -n 10000

Cheers
Alex

**Comment by chaimol** [comment]
I am also face this question, may be not add `--outSAMtype BAM SortedByCoordinate` may solve this problem.
I think it may be couse of too much file need edit .even though set `ulimit` nothing have change.

**Comment by alexdobin** [comment]
Hi Frank,

indeed, not using --outSAMtype BAM SortedByCoordinate will solve this problem.
Also, reducing the number of threads will solve it as well.
You may need sudo privileges to change the ulimit values.

Cheers
Alex

**Comment by filipegithubfigueiredo** [comment]
Both increasing the limit (-n 10000) or --outSAMtype BAM Unsorted worked for me in STAR 2.7.1a, with 60 threads.

**Comment by scseekers** [comment]
Hi Everyone 

While using `STAR v2.7.6a` I faced a similar issue. I confirm that all you have to do is to reduce threads and no need to remove `--outSAMtype BAM SortedByCoordinate` in case if that's what you are interested in.

**Comment by thalleco** [comment]
Hey, Alex, how are you?

I got the same error as scottkall.

`BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file ./_STARtmp//BAMsort/20/15`

I'm running STAR v. 2.7.3a and the following command to align RNA-Seq reads:

`nohup STAR --runThreadN 90 --twopassMode Basic --twopass1readsN -1 --genomeDir star-per-sample-2pass-analysis/starIndexes/ --readFilesIn SRR14690814_1.fastq,SRR14690814_2.fastq --outSAMtype BAM Unsorted SortedByCoordinate &`

I'm using a server with 96 CPUs, 2 threads per core.

I'm very new to STAR and RNA-Seq analysis and I'd like to get some insights about the source of this error. I did some googling but I'm still confused.

I tried reducing the number of threads to 80, 60, 32...all yielded the same error. It only worked with 16 threads. 

Then, my RAM and Swp usages were of 299/376G and 90/128G, respectively. Would that scenario yield this error?

Thank you in advance.

Thalles

**Comment by aubreybailey** [comment]
Swap should never be above 5 or 6 GB (maybe 10 is allowed?) in a healthy
compute environment. 90 means you exhausted physical memory quite a while
ago.
If I remember correctly some OS settings reserve a small % for the root
user, which is why you won't see 100% physical usage.

Unless you're doing single cell, there's no reason to use any version
higher than 2.5.3, and you can pour 90 cores into that version without
blowing up your memory.
Also from memory, SortBam is the flag that chews up the most memory. You
can always sort with samtools later.

**Comment by thalleco** [comment]
Hey, Audrey,

Gotcha, I just warned the server administrator about this Swap usage. 
I'm very new to computing and I didn't know it should never be above 5 GB. 

I'm not doing single cell yet. I will, eventually. But I'm using the 2.7.3a once its the one available in the server. Other ppl here in the lab use it as well. I'll check the possibility of using the version you mentioned. Thanks.

> Also from memory, SortBam is the flag that chews up the most memory. You can always sort with samtools later.
> […](#)

By that, are you saying that I could use  `--outSAMtype BAM Unsorted`, i.e., getting rid of `SortedByCoordinate`?

I was using this option the reduce the amount of disk usage. Okay, I'll study about samtools. 

Thanks for the insights,

Thalles

**Comment by alexdobin** [comment]
Hi Thalles, Audrey,

In my experience, using >~20 threads does not increase speed as it's limited by disk I/O.
The error you see can be fixed by increasing max number of allowed open files with
```ulimit -n 10000```
You may need to ask your sys-admin if you do not have sudo privilege.

**Comment by thalleco** [comment]
Hello, Alex.

> In my experience, using >~20 threads does not increase speed as it's limited by disk I/O.

Gotcha, thanks. 

I removed the `SortedByCoordinate` and it worked perfectly.

Thanks so much.

Thalles
