### ISSUE TITLE
Segmentation fault with small genome and many seqs and adjusted mapping parameters

### ISSUE THREAD

**Issue by ulah** [alexdobin/STAR#566]
Hi Alex,
I'd like to use star to map to some pseudo-genomes. They have usually ~1k contigs and a size of ~800kb-1Mb.
So far, everything works fine but I started quite recently to get segmentation faults during the mapping stage:

```
Feb 11 16:33:25 ..... started STAR run
Feb 11 16:33:30 ..... loading genome
Feb 11 16:33:30 ..... started mapping
Segmentation fault
```

I'm using your formula to adjust --genomeSAindexNbases and --genomeChrBinNbits, but they don't seem to be accurate enough for my edge-case. For example:

Mapping to an index created from a file with 1023 sequences and a genome size of 767556bp with

```
STAR --runMode genomeGenerate --runThreadN 12 --limitGenomeGenerateRAM 36000000000 --genomeChrBinNbits 9 --genomeSAindexNbases 7 --genomeDir /foo/bar/STAR_idx --genomeFastaFiles /foo/bar/Seqs.fasta
```

works, but any values greater than that for genomeChrBinNbits or genomeSAindexNbases fails with the seg fault. I have read somewhere that increasing "alignWindowsPerReadNmax" to 200000 could help, but it did not in my case.

I would be very grateful for any suggestion!
Best,
Urs

**Comment by alexdobin** [comment]
Hi Urs,

these scaling formulas are just a guide, and you actually need to reduce the numbers until seg-faults disappear. The formulas are derived for completely random genomes, in reality it all depends on k-mer distributions.

Cheers
Alex

**Comment by ulah** [comment]
Hi Alex,
Thanks for the fast response! Your answer is, however, a little unsatisfactory ;)
Could you please explain in what way it depends on the k-mer distribution? If I'm calculating the k-mer dist, how can I get a better estimate from this for the parameters? And why is it terminating in a seg fault in the first place?
Cheers,
Urs

**Comment by alexdobin** [comment]
Hi Urs,

I agree that this is unsatisfactory, but reducing these parameters actually solves the problem.
If you do not want to deal with estimations, you can just make this parameter very small (say --genomeSAindexNbases 4). Note that mapping results should not depend on the value, though it may reduce the mapping speed mildly.

The segfault happens when there are too many k-mers that are missing from the genome. I do need to re-design the indexing algorithm to avoid this and other similar problems, which I hope to do in the near future.

Cheers
Alex
