### ISSUE TITLE
Name sorted output

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#585]
Hello,

I was wondering if STAR can output name sorted alignment files (sam or bam is fine).

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

STAR does not sort by read name - however, we seldom need true sorting by name, as names do not have any meaning. STAR Unsorted output keep the read mates together which is sufficient for most downstream analyses. If you want to keep unmapped mates together, you can use 
--outSAMunmapped Within KeepPairs

Cheers
Alex

**Comment by freekvh** [comment]
Well, I happen to want name sorted reads because I need the bams as input for disambiguate :)

I map to both human and to mouse and then see where each reads maps better. However, and I'm sorry to hijack this thread, my bam file from the mouse refgenome and the human refgenome have a different number of lines. At first I though this was because unmapped reads are discarded but even with `--outSAMunmapped Within` I have fewer lines in my mouse bam than in the human bam. How can this be? Are multimapped reads each on a different line, represented multiple time in a bam file?

**Comment by alexdobin** [comment]
Hi @freekvh 

Yes, each alignment for a multimapping read is reported on a separate line (or 2 lines for PE reads).
There is no other way to output multimappers in SAM/BAM format - each alignment has to have it's own line.

Cheers
Alex

**Comment by freekvh** [comment]
Ok, thanx then I guess the makers of disambiguate have kept this in mind (but I shall verify).
