### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by jphe** [alexdobin/STAR#668]
Hi,

I met an error with STARsolo, it reports 'terminate called after throwing an instance of std::out_of_range' what():  basic_string::substr. '. 

I have checked the issue before, but generally are for index file. In my case, some data can run successfully while some corrupt with the error above, but both dataset using the same index.

Attached is the STARsolo log file.

Thanks,
Jphe

[ControlLog.txt](https://github.com/alexdobin/STAR/files/3317477/ControlLog.txt)

**Comment by alexdobin** [comment]
Hi Jphe

mapping seems to go through the first pair of files without a problem:
mate 1:   ../../fqs/5958_BA9.Control.T1.p2.fq.gz
mate 2:   ../../fqs/5958_BA9.Control.T1.p1.fq.gz

The problem occurs with mapping of the 2nd pair:
mate 1:   ../../fqs/5958_BA9.Control.T2.p2.fq.gz
mate 2:   ../../fqs/5958_BA9.Control.T2.p1.fq.gz.

This is probably some kind of formatting error. How did you make these files? You would need to make sure they have standard fastq formatting. Obvious formatting errors occur at the beginning and end of the files, you can visually check them with head and tail.
If the formatting error is not obvious, you can catch it using the following strategy: map just the 2nd pair  ../../fqs/5958_BA9.Control.T2.p2.fq.gz  ../../fqs/5958_BA9.Control.T2.p1.fq.gz, and do the binary search with the --readMapNumber to catch the read that causes the problem.

Cheers
Alex

**Comment by doliv071** [comment]
Hi Alex, 

I wanted to follow-up on this because I'm not sure if this is a bug or just a QC issue on my end. 
I am getting the same `std::out_of_range` error. I used the approach you mentioned with 
`--readMapNumber` to track down the read pair that seems to be causing the error.

Read 1
```
@A00814:164:HNMV7DMXX:1:1108:20211:5963 1:N:0:CCACTACA
CCGTGCCCTGTC
+
FFFFFFFFFFFF
```
Read 2
```
@A00814:164:HNMV7DMXX:1:1108:20211:5963 2:N:0:CCACTACA
GACAGGGCACGG
+
FFFFFFFFFFFF
```
Obviously, both of these reads are too short to be useful, but is there a minimum size expected by STARsolo that is throwing this error? 

This is a 10X dataset, I've attached the log below. Thanks so much for your help.

[Sample_YD-8732_HD5_StarSolo.Log.out.txt](https://github.com/alexdobin/STAR/files/4387325/Sample_YD-8732_HD5_StarSolo.Log.out.txt)

**Comment by alexdobin** [comment]
Hi David,

in your example, the issue is that the length of the barcode read is only 12b, but by default, STAR assumes v2 chemistry with 16b CB and 10b UMI. The read length is not checked because you used --soloBarcodeReadLength 0. You need tp specify the correct barcode geometry with the parameters below.

Cheers
Alex
```
soloCBstart                 1
    int>0: cell barcode start base

soloCBlen                   16
    int>0: cell barcode length

soloUMIstart                17
    int>0: UMI start base

soloUMIlen                  10
    int>0: UMI length
```

**Comment by doliv071** [comment]
Thanks Alex,

Sorry I haven't had time to test this parameter (plan to over the next week). I guess what I'm confused about is what exactly `--soloBarcodeReadLength` is doing. If I set it to 
`--soloBarcodeReadLength 26` will it only accept reads of length 26bp? In my case the majority of reads are between 26 and 28bp.

Also, I'm re-reading the manual to make sure it isn't obvious there what behavior to expect and now I'm not sure if `--soloBarcodeReadLength` only accepts 0 or 1 

Thanks again,
Dave
