### ISSUE TITLE
Mark duplicates for single-end genomic and transcriptomic mappings

### ISSUE THREAD

**Issue by fgypas** [alexdobin/STAR#671]
Hi

I run STAR for single-end reads as following:

```
 STAR --runMode alignReads \
 --twopassMode Basic \
 --runThreadN {threads} \
 --genomeDir {input.index} \
 --sjdbGTFfile {input.gtf} \
 --readFilesIn {input.reads} \
 --readFilesCommand zcat \
 --outFileNamePrefix {params.outFileNamePrefix} \
 --outSAMtype BAM SortedByCoordinate \
 --quantMode TranscriptomeSAM) &> {log}"
```

This means that I have a genomic and a transcriptomic mapping. I want to mark the duplicates but it seems that the option "--bamRemoveDuplicatesType" works only for paired-end reads.

What is the recommended way to mark the duplicates for the genomic and transcriptomic alignment I have?

Thank you in advance
Foivos

**Comment by alexdobin** [comment]
Hi Foivos,

removal of duplicates for single-end reads is problematic, as for highly expressed genes you would often find fragments that start at exactly the same position by accident rather than PCR dupliction. For PE reads, the duplication event is called only if both the starts and ends of the fragments coincide, which is less likely to happen by accident. For a general duplicate removal, including single-end reads, you can try
`samtools rmdup -s` .

Cheers
Alex

**Comment by fgypas** [comment]
Great. Thanks a lot for the quick response. Ι am closing the issue.
