### ISSUE TITLE
Primary alignment versus Secondary alignments

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#675]
Hello,

I finished mapping my samples using STAR and as I was combing through the results I found that for a particular read the primary alignment has more mismatches than the secondary alignment. I checked and found that the secondary alignment reports the correct splice junction whereas the primary alignment fails to do so. Is there any mode in which STAR could be run to make sure that the primary alignment is always "better" than the secondary alignment? Here are the two alignments of the read.

```
HWI-ST373:283:D1FBEACXX:1:1207:16232:85642	16	4	18013044	3	75M89N26M	*	0	0	GCCACATTCATATGCCAAGTCCTCAGCAGTTGTAAGTGCGATACGAGGAGTGATGATACGCTCAATAGTGGGGTCGTTTGCCAAGTTAAGGAAAAGAGTCA	2:4:>DC@@CC@@?>(3?9((9:;@>>:CA>:C>=9,5(=.-(53;==@C;B<FB@@?(9?D9B4D:01D<FE@)+EFCA::HBA??E:BFCB>D?BD=7@	NH:i:2	HI:i:1	AS:i:93	nM:i:3	NM:i:3	MD:Z:20A54A0C24	jM:B:c,1	jI:B:i,18013119,18013207	XS:A:+
HWI-ST373:283:D1FBEACXX:1:1207:16232:85642	272	4	18013044	3	81M89N20M	*	0	0	GCCACATTCATATGCCAAGTCCTCAGCAGTTGTAAGTGCGATACGAGGAGTGATGATACGCTCAATAGTGGGGTCGTTTGCCAAGTTAAGGAAAAGAGTCA	2:4:>DC@@CC@@?>(3?9((9:;@>>:CA>:C>=9,5(=.-(53;==@C;B<FB@@?(9?D9B4D:01D<FE@)+EFCA::HBA??E:BFCB>D?BD=7@	NH:i:2	HI:i:2	AS:i:93	nM:i:1	NM:i:1	MD:Z:20A80	jM:B:c,4	jI:B:i,18013125,18013213	XS:A:-
```

I retried by setting the --outSAMprimaryFlag AllBestScore but then both the alignments were marked primary.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

STAR calculates the alignment score as a measure of goodness of the alignment, with +/-1 for matches/mismatches, and user-definable penalties for indels and junctions. The primary alignment is chosen to have the highest score. 

In this case the alignment score is exactly the same for both alignments, AS:i:93, because the first one has GT/AG intron motif (jM:B:c,1) and 3 mismatches, while the 2nd one has CT/GC (jM:B:c,4, rev-compl of GC/AG). The former - canonical - motif has 0 penalty, while the latter - "semicanonical" motif - has --scoreGapGCAG -4 penalty which is exactly equivalent to the penalty of two mismatches.

You can tweak the penalty parameters to achieve the desired results in terms of alignment score and output of multimappers. E.g., you can use --scoreGapGCAG -3, which will make the 2nd alignment primary. However, it will affect all alignments and can make the results "worse" in other cases.

Cheers
Alex
