### ISSUE TITLE
STAR produces very long split alignments

### ISSUE THREAD

**Issue by ersgupta** [alexdobin/STAR#688]
I am trying STAR and hisat2 on my RNAseq data. Surprisingly, STAR produces very long split alignments whereas hisat2 seems to produce better alignments. Any ideas of what could be going wrong?

parameters used:
STAR (v2.7.1a): --outSAMstrandField intronMotif --twopassMode Basic (rest default)
hisat2: --dta

The top and bottom alignments are from STAR (2-pass) and hisat2, respectively.
![Screenshot from 2019-07-16 08-35-53](https://user-images.githubusercontent.com/5276459/61272707-0b73e600-a7a8-11e9-90d9-67d70a28e96c.png)

**Comment by ersgupta** [comment]
Solved by setting ```--alignIntronMax 10000``` from the very high default ```--alignIntronMax 589824 (2^16*9)```.

**Comment by ersgupta** [comment]
I wonder if it is possible to reduce the default or have a ```--plant``` option to set defaults more closer to plants.

**Comment by alexdobin** [comment]
Hi Saurabh,

I am a bit reluctant to add preset options, as it will hide the actual complexity of alignment parameters choice from the users. For instance these long splices might be real in some cases - I wonder if they are not "detected" in plants because they are discarded early on in the analysis. There is actually another - "softer" - option to filter them out:
--outSJfilterIntronMaxVsReadN        50000 100000 200000
   N integers>=0: maximum gap allowed for junctions supported by 1,2,3,,,N reads
   i.e. by default junctions supported by 1 read can have gaps <=50000b, by 2 reads: <=100000b, by 3 reads: <=200000. by >=4 reads any gap <=alignIntronMax
This needs to be used with --outFilterType BySJout to affect the SAM/BAM file.

Cheers
Alex

**Comment by ersgupta** [comment]
Hi Alex,
Thanks. Then maybe a small note regarding this in the manual would be helpful, because my concern is that the default parameters produce many false secondary alignments (in case of plants atleast, Arabidopsis in this case).

I will be using only the primary alignments for further analysis. I would expect these split alignments to carry a lower mapping score. So do you reckon it is safe to go ahead with defaults and then filter the bam to retain primary alignments only?

Regarding ```--outSJfilterIntronMaxVsReadN 50000 100000 200000```, isn't it set as default? or? Also in this option is there any way to specify the number of reads, instead of 1,2,3..N based on the order.

regards
Saurabh
