### ISSUE TITLE
STAR-STAR_2.4.0f1 crashes with zero length reads

### ISSUE THREAD

**Issue by rvijaya** [alexdobin/STAR#7]
EXITING because of FATAL ERROR in reads input: short read sequence line: 1
Read Name=@M01750:160:000000000-ABY8Y:1:1103:6900:8107
Read Sequence====
DEF_readNameLengthMax=50000
DEF_readSeqLengthMax=500

Nov 14 21:03:24 ...... FATAL ERROR, exiting

The read is actually 0 bases long. STAR_2.3.0e handles this gracefully. It will be nice if future versions of STAR handle this gracefully as well.

**Comment by patidarr** [comment]
getting this error on 2.5.2a,

EXITING because of FATAL ERROR in reads input: short read sequence line: 1
Read Name=@R0212989:345:C4K7CACXX:4:1101:6604:1961
Read Sequence====
DEF_readNameLengthMax=50000
DEF_readSeqLengthMax=650

Oct 03 09:34:10 ...... FATAL ERROR, exiting


Any solution for this? any particular version which I can use which filters zero length reads instead of throwing FATAL ERROR.

**Comment by alexdobin** [comment]
Hi Rajesh,

please do not comment on closed issues as I may not see it right away. It's better to start a new issue.
Zero-length reads are not really allowed by the FASTQ format, and they create all kinds of problems - e.g. they cannot be output into the BAM file. I think it's best to prevent the pre-mapping software (trimmers) from creating them. You can also replace the zero length sequences with one or more "N" (and corresponding length of the quality string).

Cheers
Alex

**Comment by patidarr** [comment]
Sorry for posting here in closed issue, I used trimmer to get the job done, I was just reluctant to change my pipeline. but working well now.

Thanks,
Rajesh
