### ISSUE TITLE
`versionGenome` is not consistent with star version

### ISSUE THREAD

**Issue by xie186** [alexdobin/STAR#739]
Here is the process to reproduce the issue: 

```
conda install -c bioconda star=2.6.1d
STAR   --runMode genomeGenerate --runThreadN 19 --genomeDir test --genomeFastaFiles GRCm38.p6_rRNA.fasta
```

```
$ STAR --version
STAR_2.6.1d
```

File: test/genomeParameters.txt
```
### STAR   --runMode genomeGenerate   --runThreadN 19   --genomeDir test   --genomeFastaFiles GRCm38.p6_rRNA.fasta
### GstrandBit 32
versionGenome   20201
genomeFastaFiles        GRCm38.p6_rRNA.fasta
genomeSAindexNbases     14
genomeChrBinNbits       18
genomeSAsparseD 1
sjdbOverhang    0
sjdbFileChrStartEnd     -
sjdbGTFfile     -
sjdbGTFchrPrefix        -
sjdbGTFfeatureExon      exon
sjdbGTFtagExonParentTranscript  transcript_id
sjdbGTFtagExonParentGene        gene_id
sjdbInsertSave  Basic
genomeFileSizes 93585408 351321

```

Thanks.

**Comment by alexdobin** [comment]
Hi Shaojun,

are you referring to 
versionGenome   20201
line?

The version here does not need to coincide with the STAR version. The 2.6.1d and earlier version used an internal "id" for the genome index version. Since 2.7.0, the version there is the true STAR version, but it tells you what is the earliest STAR version for genome index that is still compatible with the current version.

Cheers
Alex

**Comment by xie186** [comment]
Got it. Thanks.
