### ISSUE TITLE
Question concerning the Gene and GeneFull STARsolo output

### ISSUE THREAD

**Issue by jcschupp** [alexdobin/STAR#740]
Hi Alex, 

I have a question concerning the Gene and GeneFull raw output of STARsolo:

We are using the Fraction of UMIs mapped to introns (relative to all reads) for downstream analysis.

If I understand the manual correctly, we would get that per Barcode by 
1-(sum(Gene)/sum(GeneFull) 

The weird issue we found  (especially in low UMI barcodes (below 2000 UMI)) is that, we see a relatively big number of cell barcodes, where the sum of all UMIs in the "Gene" output is bigger then the sum of UMIs in the "GeneFull" output (for the same barcode of course).

Is there any logical explanation for this behaviour?

Thanks in advance
Jonas

**Comment by alexdobin** [comment]
Hi Jonas,

A possible explanation is as follows.
Gene counting requires reads to be fully concordant with gene transcript, while GeneFull counting requires a simple overlap of reads region with the gene region. In both cases, if a read is consistent with more than one gene, it will be considered ambiguous and not counted. Since the GeneFull counting is less restrictive, it can result in more ambiguities for overlapping gene, and hence lower counts for GeneFull.

Imaging a gene inside an intron of another gene. All reads mapping to this gene exons will be counted for Gene, but ambiguous for GeneFull.

You can check out a few cases on the browser, selecting the BAM entries for a specific cell barcode.
If you find an example that cannot be explained as above, I can take a close look at it.

I guess I could work out a more sophisticated GeneFull policy, where concordant matching of gene transcripts takes priority over non-concordant, to reduce the ambiguity.

Cheers
Alex

**Comment by jcschupp** [comment]
Hi Alex,
thanks for the response!

As to your suggestion of changing the GeneFull policy, my understanding of the whole subject here is too limited, so I cannot really comment on this...
 
Thanks again, 
Jonas
