### ISSUE TITLE
Problem with generation of bam file

### ISSUE THREAD

**Issue by CuypersBart** [alexdobin/STAR#741]
Hi All,

I get the error 

"EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: Expected bin size=3071483410 ; size on disk=822083584 ; bin number=44

Sep 18 07:55:39 ...... FATAL ERROR, exiting"

with STAR-2.7.2b

Reading some previous issues:
- I dropped the number of cores from 28 to 8, but did not resolve the issue.
- Outputting everything in a different folder, but does not resolve the ussue.

Best Regards,

Bart

**Comment by alexdobin** [comment]
Hi Bart,

this often happens when you do not have enough space on disk... please check that you have enough space, I would have ~100GB or more free.
Also please remove all the contents of the run directory before the next run, and make sure no other STAR jobs are running in the same run directory.

If this does not help, please send me the Log.out file.

Cheers
Alex

**Comment by CuypersBart** [comment]
Dear Alex,

thank you a lot for the fast reply. That was indeed the problem, but I did not realise as there was still space left on the drive (but not 100GB). 

Cheers,

Bart
