### ISSUE TITLE
Filtered counts from STARsolo lower than that from cellranger

### ISSUE THREAD

**Issue by bapoorva** [alexdobin/STAR#824]
Hi,

I ran the cellranger and STARsolo on the same dataset. I even used the same reference genome

```
 ~/bin/STAR  --runMode genomeGenerate --runThreadN 48 --genomeDir GRCh38_STARsolo --genomeFastaFiles  cellranger_reference/refdata-cellranger-GRCh38-3.0.0/fasta/genome.fa --sjdbGTFfile cellranger_reference/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf

~/STAR/STAR-2.7.3a/bin/Linux_x86_64_static/STAR --soloType CB_UMI_Simple --soloUMIlen 12 --soloUMIfiltering MultiGeneUMI --soloCBmatchWLtype 1MM_multi_pseudocounts --soloCBwhitelist ~/NGSshare/3M-february-2018.txt --readFilesIn ~/Desktop/EEM_R2_001.fastq.gz ~/Desktop/EEM_R1_001.fastq.gz --genomeDir ~/NGSshare/GRCh38_STARsolo --runThreadN 64 --readFilesCommand zcat --soloBarcodeReadLength 0 --outSAMtype BAM Unsorted --outFileNamePrefix ~/Desktop/EEM

```
Yet somehow the number of filtered cells  is different in both cases. I ran both emptydrop and defaultdrops from [DropletUtils](https://bioconductor.org/packages/release/bioc/manuals/DropletUtils/man/DropletUtils.pdf) package in bioconductor. 

```
dir="~/Desktop/EEM/raw"
outdir = "~/Desktop/EEM/filtered"

dir.create(outdir,recursive = T)
sce <- read10xCounts(dir)
ct <- counts(sce)
empt.drops <- emptyDrops(ct)
is.cell <- empt.drops$FDR <= 0.01
sum(is.cell, na.rm=TRUE)
def.drops <- defaultDrops(ct)
```
According to the documentation, defaultDrops function is an exact reproduction of the cellranger algorithm. While the numbers correspond to the results from STARsolo, it doesn't to cellranger 

Here are the results

```

            | raw     | filtered | empty_drop | default_drop(def)
cell ranger | 6794880 | 14200    | 51650      | 8402
   Starsolo | 6794880 | 8402     | 51405      | 8400


```
Any reason why ? Or should i be giving it a different input parameter?

Thanks,
Apoorva

**Comment by alexdobin** [comment]
Hi Apoorva,

thanks for this interesting investigation. I was not aware of the defaultDrop tool before.

8,402 vs 8,400 with default drop looks like a very good agreement for me... :)
One thing to check - have you tried to run defaultDrop on CellRanger raw counts?
Does this generate exactly the same filtered cells as CellRanger?

Also, to achieve a better agreement with CellRanger, you would need to use --genomeSAsparseD 3 which CellRanger uses to generate STAR genome.

I will try to investigate this a bit more this week.

Cheers
Alex

**Comment by bapoorva** [comment]
Hi Alex,

Yes. I did defaultdrop on cellranger raw counts. The results are tabulated above and I got 8402 again. That is why I created this issue.. To understand what STARsolo/Cellranger is doing different in the filtering step.

I will try --genomeSAsparseD 3 on my dataset and see what I get. 

Thank you
Apoorva

**Comment by alexdobin** [comment]
Hi Apoorva,

ahh, I think I did not get what the table meant the first time.
So, the CellRanger "filtered" cells directory contains 14,200 cells and defaultDrops on CellRanger raw cells yields 8,402 cells? This would indicate that defaultDrops does not work the same as CellRanger filtering. Moreover, it's very close to the STARsolo built-in filtering, which in turn tries to replicate CellRanger v2 filtering. This means that defaultDrop filtering was designed to match CellRanger v2.
So I do not think the problem is in the raw counts, and thus --genomeSAsparseD 3 is not going to help. :(

CellRanger v3 filtering "is based" on EmptyDrops, but it's clearly not equivalent to it.
Please see this thread https://github.com/alexdobin/STAR/issues/801 - theEmptyDrops parameters suggested by @tilofreiwald may help with getting more similar numbers to CellRanger v3.

Cheers
Alex

**Comment by bapoorva** [comment]
Hi Alex,

I tried the script as suggested by @tilofreiwald and I got completely different numbers that agrees with neither of the results I got previously from cellranger and Emptydrops. Cellranger gave 14200 cells, Emptydrops gave 51650cells and Defaultdrops 8402cells. However, this new script gives me 35978. I went through the cellranger script and I'm failing to understand how they are doing the filtering. 

defaultDrop matches cellranger v2 results perfectly but not v3. But I'm afraid I may be losing more cells by using STARsolo. Thoughts?

Thanks,
Apoorva

**Comment by alexdobin** [comment]
Hi Apoorva,

I think the only way to match CR results is to reimplement the CR filtering scheme. It would be great if someone could volunteer to do it. :) If not, I will try to work on it in the next 1-2 weeks.

Cheers
Alex

**Comment by fengkuangbaozha** [comment]
Hi Alex,
Just want to know when can CR3 filtering scheme add in the STARsolo. I had exactly the same issue as Apoorva had. However, I found STARsolo is so easy to use and I do not want to switch back to CR. Thanks in advance. 

Best,
Yidan

**Comment by alexdobin** [comment]
Hi Yidan,

you are just in time to test it! :)
It's in the develop branch:
https://github.com/alexdobin/STAR/tree/develop

You can either use it in the normal STARsolo run with ```--soloCellFilter EmptyDrops_CR```
or
use it on previous STARsolo run with
```STAR --soloCellFilter EmptyDrops_CR --runMode soloCellFiltering /path/to/Solo.out/Gene/raw/ /path/to/output/prefix```

Please let me whether it works for you.

For better compatibility with CR 3.1.0, you need to use 
```--soloUMIfiltering MultiGeneUMI --soloCBmatchWLtype 1MM_multi_pseudocounts``` in STARsolo run.

Cheers
Alex

**Comment by fengkuangbaozha** [comment]
Dear Alex,

Thanks so much for your reply.
It worked amazing. I just tested one sample now:

5324 cells with CR4.0, 
5284 cells with STARsolo empty_drop,
3100 cells with STARsolo cell ranger v2

But I will add the CR3 compatible parameter and run all samples again, and send you the comparison table next week.

Plus "--runMode soloCellFiltering" is so easy to use. Is it possible to also implement counting step as a standalone function, like "--runMode soloCountsFromBam”. 
Because it will be much easier for single cell allele specific analysis. I run the STARsolo first to get the bam, then separate alleles based the SNP info, afterwards I want to count UMI based on barcode info using the separated bam. Currently I am using UMItools count to do the job, but for me it is better to stick to STARsolo since the result will be more consistent. Let me know how you think about this.

Thanks again for your genius work.

Best,
Yidan

**Comment by alexdobin** [comment]
Hi Yidan,

thanks for testing it! The agreement looks good. I am working on an even better agreement for CR4, which should be ready by the end of the week.

Your other request is much more complicated, unfortunately. Reading from a BAM is on my radar, however, I cannot give you an ETA, it's unlikely to happen until late fall.

Cheers
Alex

**Comment by fengkuangbaozha** [comment]
Hi Alex,

I tested all my samples with CR3 compatible parameters, here is the result:

Sample	CR4.0	STARsolo_empty_drop
WT_rep1	5324	5326
WT_rep2	10356	10384
KO_rep1	8731	8553
KO_rep2	7659	7021

I also did downstream analysis with Seurat, the cluster pattern are almost the same. 
Overall, I think it works very well for my datasets, so I totally switched to STARsolo now.
Let me know if your CR4 version is ready, I would love to test it.

For the other function, reading from a BAM, I can use UMItools instead. Do not pressure yourself please, but let me know when it is out. Thanks again for your amazing work. 

Best,
Yidan

**Comment by alexdobin** [comment]
Hi Yidan,

Sounds great, thanks for letting me know!
The ETA for CR4 is the end of the next week now. :(
Hopefully, the differences you are seeing in KO samples will go away.

Cheers
Alex

**Comment by bapoorva** [comment]
Hi Alex,

Sorry it took me a while to dig for the data and test it. The development version works. Got 9722 cells from CR and 9710 from STARSolo. Thank you very much

Apoorva
