### ISSUE TITLE
% aligned to transcriptome

### ISSUE THREAD

**Issue by LuciaJim** [alexdobin/STAR#826]
Hi Alex,

The data I'm working on is scRNAseq whole cells from 10X, so I'm specially interested in the Summary.cvs implemented in starSOLO2.7.3a.

If I understood well, star will only take the exon category as input for the percentage of reads confidently mapped to the transcriptome. Is it is right? Does it make any difference in the % aligned to have also other categories such as gene, CDS star_codon, stop_codon, transcript, five_prime_utr, 3_prime_utr?

Thank you,

Lucía

**Comment by alexdobin** [comment]
Hi Lucía

the Summary.csv is generated for each --soloFeatures separately.  If you use GeneFull, it will show the % of reads overlapping full genes (i.e. exons+introns). For other features, at the moment, you would need to rerun STAR with --sjdbGTFfeatureExon <feature>, which will operate on features other than "exon" .

Cheers
Alex

**Comment by LuciaJim** [comment]
Thus, if we compare the alignment result of one GTF with with all those categories (such as the Ensembl one) and the same GTF only containing the exon category in the 3rd column with the following commands:  --sjdbGTFfeatureExon default --soloFeatures default; the output for the % reads mapped to transcriptome will be the same, while there could be an increase in the % reads mapped to Genome, isn't it?

**Comment by alexdobin** [comment]
Hi Lucía

I am not sure that I followed your question.
"Feature" means different things for ```--sjdbGTFfeatureExon``` and ```--soloFeatures```

For other GTF features (column 3), if you use ```--sjdbGTFfeatureExon CDS```, STAR will consider the CDS lines in the GTF instead of exon lines. The counts will be aggregated by gene_id in CDS lines.

The ```--soloFeatures Gene``` option counts only the reads that map entirely in the GTFfeature (exon, CDS etc) boundaries.
The ```--soloFeatures GeneFull``` option counts all reads that overlap the gene region between the all the GTFfeatures that belong to the same gene.

The defaults are ```--sjdbGTFfeatureExon exon    --soloFeatures Gene```

Cheers
Alex

**Comment by LuciaJim** [comment]
Hi Alex,
Thank you, is much clearer now.
My question comes from the comparison of an Ensembl gtf and the same gtf enriched with new RNAseq data containing only exon info, so I wanted to know up to what extent the increase in the % reads mapped to transcriptome using  `--sjdbGTFfeatureExon exon --soloFeatures Gene` was due to the enrichment in new exons or if the other cathegories could have an slight effect.

Best,
Lucía

**Comment by alexdobin** [comment]
Hi Lucía

since --sjdbGTFfeatureExon CDS/UTR etc are subsets of --sjdbGTFfeatureExon exon, the counts should be smaller in the former case. On the other hand, switching from --sjdbGTFfeatureExon  Gene to --sjdbGTFfeatureExon GeneFull should increase the counts (for all categories) since the reads overlapping introns will be added.

Cheers
Alex
