### ISSUE TITLE
128gb ram not enough to generate human genome

### ISSUE THREAD

**Issue by pattakosn** [alexdobin/STAR#871]
Hi, I was trying to generate genome for the human dna using the ```Homo_sapiens.GRCh38.dna.toplevel.fa.gz``` file i downloaded from ensemble.

```
EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 168632718037 and make that much RAM available 

```

I tried using ```--genomeChrBinNbits 15``` and/or ```-limitGenomeGenerateRAM 128000000000``` but I still get the same error. I have no idea whether this is a reasonable requirement for the star tool (as I am a complete novice in bioinformatics) but it was suggested to me from the biostar forum that it is an unusually high requirement so I thought you may be interested in it or able to provide a solution. Thank you

**Comment by alexdobin** [comment]
Hi @pattakosn 

please use the "primary_assembly" file instead of "toplevel", e.g.
http://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
The toplevel file contains patches and alternative loci which are not needed for normal RNA-seq analyses.

Cheers
Alex

**Comment by pattakosn** [comment]
Hi @alexdobin , thank you for your advise. I already did this but I thought that this may be a bug that is why I posted this. Thank you.
