### ISSUE TITLE
DOS formatted FASTQ text as an input

### ISSUE THREAD

**Issue by jhart99** [alexdobin/STAR#91]
This took me a few days to track down where it was all going wrong.  I think that the issue should be solved in STAR and not RSEM.

Issue:
Start with a DOS formatted FASTQ file where lines end with \r\n rather than \n
Align this with STAR with alignedtotranscriptome output
Feed the transcriptome alignment into RSEM.
RSEM errors out with an error about how a base quality score is out of range.

Can be resolved by stripping out the \r from the lines using the following command
zcat test.fq.gz | sed 's/^M$//' | gzip >test2.fq.gz

After stripping them, everything works as expected.  If needed I can attach a limited gzipped fastq file which displays this behavior as well as the command lines I used specifically.

**Comment by alexdobin** [comment]
Hi Jonathan,

I will code stripping of ^M from the end of the sequences.

For now, you can do it on the fly with process substitution:
--readFilesIn <(zcat test.fq.gz | sed 's/^M$//')
or you can write a script zcatTrim.sh:
zcat $1 | sed 's/^M$//'
and make STAR use it instead of zcat
--readFilesIn test.fq.gz --readFilesCommand /path/to/zcatTrim.sh

Cheers
Alex

**Comment by jhart99** [comment]
Yep already solved it using a script, thanks for having a look at it.  

Have a good one
Jonathan
