### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by aleksandrzenin** [alexdobin/STAR#99]
Hello, I get some strange error:
```bash
ubuntu@ip:/mnt/temp3$ /usr/STAR/source/STAR --runThreadN 32 --genomeLoad LoadAndKeep --genomeDir /mnt/data/index/ --outFileNamePrefix star_output --readFilesIn L001_R1_001.fastq L001_R2_001.fastq
Jan 14 19:23:22 ..... Started STAR run
Jan 14 19:23:22 ..... Loading genome
Jan 14 19:23:22 ..... Started mapping
Bus error (core dumped)
```
Previous release 2.5.0b works fine.

**Comment by biosyssun** [comment]
Oh! I have the same error.

**Comment by alexdobin** [comment]
Hi @aleksandrzenin , @biosyssun

is this error happening in the 2.5.0c release, or in one of the later patches on master (starting from a5975c2)?

If the latter is the case, please check the latest patch on master that's supposed to fix the problem.
If it does not help, please send me your Log.out file of the failed run.

Cheers
Alex

**Comment by aleksandrzenin** [comment]
Sorry, I don't know which commit it was, I just did ```git clone``` your repo a day ago. Latest commit works, thanks.

**Comment by bearbob** [comment]
I had to switch machines lately and encountered this bug in the current release Version (2.5.2a) as well as in the current commit 30ef216. 
It worked like a charm a few days ago, so I guess the problem is changing the machine, which I cannot undo. Any ideas are appreciated, thanks!
[Log.txt](https://github.com/alexdobin/STAR/files/338917/Log.txt)
